### ISSUE TITLE
get-device-spec does not check persist.sys.locale

### ISSUE THREAD

**Issue by TE-tatuonagamatu** [google/bundletool#1]
**Describe the bug**
budletool get-device-spec returns device's supportedLocales. I'm using Japanese locale on my Nexus 5X (8.1.0). But get-device-spec returns only en-US locale as follows:

<pre>
{
  "supportedAbis": ["arm64-v8a", "armeabi-v7a", "armeabi"],
  "supportedLocales": ["en-US"],
  "screenDensity": 420,
  "sdkVersion": 27
}
</pre>

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]

**To Reproduce**
Connect Nexus 5X with Japanese locale and execute next command

<pre>
java -jar ~/Downloads/bundletool-all-0.3.3.jar get-device-spec --output=/tmp/1.json
</pre>

**Expected behavior**
"ja-JP" is included in supportedLocales section

**Known workaround**
none

**Environment:**
OS: Android 8.1.0

**Additional context**
Need to check persist.sys.locale property

**Comment by plecesne** [comment]
Thank you for reporting the issue.
We are aware of this limitation and will be fixing it soon.

**Comment by plecesne** [comment]
Thanks for the contribution!
