### ISSUE TITLE
trying to run the source code, but com.android.bundle package not found inside source

### ISSUE THREAD

**Issue by Shihab-BD** [google/bundletool#101]
**Describe the bug**

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: [e.g. iOS 10.3.3]

**Additional context**

**Comment by plecesne** [comment]
You didn't provide any description, stacktrace, ways to reproduce, etc. which makes it difficult to help you. The template for the bug is here for a reason; it helps us help you more efficiently.

**Comment by Shihab-BD** [comment]
![Capture](https://user-images.githubusercontent.com/26686497/62059285-c4c0ca00-b244-11e9-86f6-9b3a6a0131e8.PNG)
When i try to build the project


import com.android.bundle.Config.BundleConfig;
import com.android.bundle.Config.Compression;
import com.android.bundle.Devices.DeviceSpec;

these can not be resolved

**Comment by plecesne** [comment]
See https://github.com/google/bundletool/issues/28 and scroll down. We haven't added official documentation on how to compile bundletool locally, but all the information should be there in this bug.
