### ISSUE TITLE
upload play store failed after enable bundle language

### ISSUE THREAD

**Issue by JingYeoh** [google/bundletool#105]
**Describe the bug**
upload play store failed after enable bundle language, i got below error:
```
Interrupted while waiting for aapt dump resources to finish
```
i can upload apk extracted by aab success, and i can upload aab success after close bundle language

**Comment by woshitangebupasui** [comment]
I have also encountered the same problem.Have you found any solutions？

**Comment by kvafy** [comment]
We have made some adjustments in Play. Could you try uploading again?

**Comment by ymakhno** [comment]
Inactive issue.

**Comment by superdiazzz** [comment]
i got this issue, when i upload aab to playstore. it failed over and over. How to solved this. The error said 
"Couldn't upload. Try again." 
Yes, i have installed bundletool to convert aab to apks but now i got this issue

**Comment by plecesne** [comment]
The error message doesn't suggest that this is a bundletool issue. Please reach out to the [Play Developer support](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en) instead.
