### ISSUE TITLE
Access style resource in split APK

### ISSUE THREAD

**Issue by Vandalko** [google/bundletool#106]
**Describe the bug**
Is there a way to access style resources from split? So, once split is installed, I can call `resource.getIdentifier(...)` and apply it for existing views.

I've built a very simple project to showcase this issue https://github.com/Vandalko/android-dynamic-feature-theming
Basically, I want to access style information that is located inside split APK:
https://github.com/Vandalko/android-dynamic-feature-theming/blob/e49957ae5d878428cc8d7a20322e262c90c5d34a/app/src/main/java/me/vandalko/dynamic_theming/MainActivity.java#L112-L127

**Bundletool version(s) affected**
Version: 0.10.2

**To Reproduce**
 - You can check built files https://github.com/Vandalko/android-dynamic-feature-theming/tree/master/binary
 - Or clone the whole repo and run install script https://github.com/Vandalko/android-dynamic-feature-theming/blob/master/install.sh
 - Once launched, it's pretty straightforward:
   - **First** button is a default theme
   - **Second** button is style resource inside base APK
   - **Third** button tries to load style from split APK

**Expected behavior**
It should be possible to use styles declared in split APK.

**Known workaround**
According to the "Known issues" section https://developer.android.com/guide/app-bundle#known_issues
Google Play still servers universal APK so it's only an issue when generating multiple APKs through **bundletool**.

**Environment:**
OS: Ubuntu 18.04.2 LTS
Java: 1.8

**Additional context:**
Android O has introduced [createContextForSplit(..)](https://developer.android.com/reference/android/content/Context#createContextForSplit(java.lang.String)) which _in theory_ should work, but **my goal is to get it working on Android M+**

**Comment by Vandalko** [comment]
I guess the root cause is similar to https://github.com/google/bundletool/issues/68

**Comment by ymakhno** [comment]
I checked out your code, you should be able to achieve what you want with `getIdentifier` if you make your dynamic feature package to be sub-package of your app: 

AndroidManifest.xml
```
package="me.vandalko.dynamic_theming.dynamic_theme"
```

MainActivity.java:
```
private static final String SPLIT_ID = "me.vandalko.dynamic_theming.dynamic_theme";
```
