### ISSUE TITLE
Installing an APKs file takes longer than 10 minutes

### ISSUE THREAD

**Issue by hanseul1795** [google/bundletool#108]
I'm using python to use bundletool.jar and to install apks file into my device. 
Subprocess.Popen([java, -Xmx3g, '-jar', BundleTool, 'install-apks', '--adb', adbPass, '--apks', outputPath], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

this is the command that I've used and the apks file size is about 900 mb(I know that I cannot upload an aab file bigger than 500mb, this is for test purpose)

Is there a solution that I can use to accelerate the process?

**Comment by plecesne** [comment]
Is it the installation that takes time or building the `.apks` file?
Does that takes less time when adb-installing a single APK of the same size?

**Comment by hanseul1795** [comment]
@plecesne it takes about 2 minutes to build the` .apks` file.

It seems like it freezes while installing the generated .apks file.
If I reduce the size of memory, I get the following error:

> ERROR: Installing apks to device failed :  The APKs have been extracted in the directory: C:\Users\HANSEU~1.SHI\AppData\Local\Temp\5498491312108569650

**Comment by plecesne** [comment]
What is the size of the extracted APKs (you may have to check them before the command completes)?

I suspect it's just `adb` slowness and nothing in bundletool we can do about, but could you confirm by trying to manually install the extracted APKs using `adb install-multiple base-master.apk config-xxhdpi.apk ...`

**Comment by hanseul1795** [comment]
Generated APks file size is about 970mb.
so to avoid the issue, should I use adb to manually install each apk files?

**Comment by plecesne** [comment]
Sorry, I didn't mean the size of the `.apks` file, but the size of the extracted `.apk` file in the directory when it says "The APKs have been extracted in the directory xxx"

I'm not saying that manually installing will fix the issue, but it will tell us where the issue comes from (whether it's an adb issue or a bundletool issue).

**Comment by hanseul1795** [comment]
@plecesne you were right about this issue, adb was the reason.
extracted apk files:  
![image](https://user-images.githubusercontent.com/32581977/62721780-f707bf80-b9da-11e9-86f8-0f405f8af628.png)

**Comment by plecesne** [comment]
This is one big APK :) 

I think you may find some help on other forums, as people have been discussing this topic and workarounds in various places.
I'll close this bug since this doesn't seem to be bundletool related.
