### ISSUE TITLE
Verify if the generated apks file is compatible with a specific device

### ISSUE THREAD

**Issue by hanseul1795** [google/bundletool#111]
I'm implementing a python script to automatically build `.aab` file and install to multiple devices.
Until now, I need to regenerate the `.apks` files each time I perform the installation.
When using `install-apks` command, is there a way to check if the selected `.apks` file is compatible with a specific device (passed with` --device-id=serial-id ` command)?

**Comment by plecesne** [comment]
Any reason you re-generate the `.apks` file each time instead of building the `.apks` once for all devices (which is what happens by default when you don't specify the `--device-spec` flag)?

**Comment by hanseul1795** [comment]
@plecesne hello and good morning. 
To explain the situation, 

1- my game engine detects the connected device(s)

2- builds the `.aab` file

3- install the `.apks` file generated from the `.aab` file to the connected device. 
(I'm passing --overwrite flag here)

So I'm generating device specific `.apks` file
(I'm passing --connected-device with --device-id=serial-id if multiple devices are connected).  

What I wanted to do is, before generating the `.apks` file, to check whether existing `.apks` file is compatible with the connected device.

I thought of generating a `.json` file from get-device-spec and verify compatibility for each `.apk` files inside the `.apks`. But I find this solution ugly...

**Comment by plecesne** [comment]
The `install-apks` command should ideally throw an exception if the connected device is not compatible with `.apks` file. I forget whether that's the case already today, but that would probably be one way of addressing the issue. Would that work for you?

**Comment by hanseul1795** [comment]
@plecesne yes, that's perfect. I could just generate the `.apks` file if an exception is thrown.
Thank you!
