### ISSUE TITLE
the generated standalone apk can't support 4.x device if Apk contains java8 lambda expressions

### ISSUE THREAD

**Issue by staney7** [google/bundletool#112]
I use bundletool to generate a standalone APK for 4.x device ,  but it can't work.  I find that when I use lambda expression in  my application code , the appliaction will crash because of NoClassDefFoundError.

**Comment by staney7** [comment]
My APK has  a dynamic module .There is three dex file in main module and one dex in a  dynamic module. And in this dynamic module , I set fusing = true .

**Comment by plecesne** [comment]
This might have been fixed with a more recent version of D8. We have plans to upgrade the version soon, but you could try to update the dependency locally in your build gradle file by setting `compile "com.android.tools:r8:1.4.93"

**Comment by staney7** [comment]
I try to set comile "com.android.tools:r8:1.4.93" in my app build gradle file, but it doesn't work for me, the application will crash too. My Android studio version is 3.4.2 , gradle version is 5.1.1 and android tool version is 3.4.2.

**Comment by ymakhno** [comment]
Core desugaring library support is implemented in bundletool 1.7.0.
