### ISSUE TITLE
Split assets by a certain dimension

### ISSUE THREAD

**Issue by woshitangebupasui** [google/bundletool#116]
**Is your feature request related to a problem? Please describe.**
We got two large files in our assets directory，like A.xz and A_64.xz.These two files are compressed file format, not the so library, but we do some optimizations for these files.Now I want to use the App Bundle to deliver these two files for different abi devices, so that we can have better performance on the package size.But we don't find a good way to solve this problem.

**Describe the solution you'd like**
We want to deliver some files in the assets directory through a certain dimension, instead of delivering all of them. 

**Describe alternatives you've considered**
We have considered changing the file suffix to .so, putting it into the directory under 'lib' for each abi, and then restoring these files from the 'lib' directory at runtime, but I don't think this is a good way to solve the problem. 

**Additional context**
No other additional context.

**Comment by kvafy** [comment]
At the moment, assets can be targeted only by language and by texture compression format.

I agree that the workaround with putting the files under lib/ is not ideal. Before Android M, the Android Platform decompresses all .so files into a special folder, meaning that the file will be present on the device twice (and, as stated, the file is large). This behavior may be also on M+, if you explicitly disabled uncompressed native libraries feature in your Gradle config.

**Comment by woshitangebupasui** [comment]
Appreciate for your reply!But how can I target assets by language or by texture compression format?I didn't find related articles on the Android Developer Docs.

**Comment by kvafy** [comment]
There is a special syntax in the following form of directory suffix `#lang_<language-code>` and `#tcf_<format>`. Examples:

```
assets/dir#lang_en/
assets/dir#lang_es/
...
```

```
assets/dir#tcf_atc/
assets/dir#tcf_etc1/
...
```

**Comment by plecesne** [comment]
There is no support for assets split by texture compression format I believe, only language.
