### ISSUE TITLE
Merge splitted APK to single APK 

### ISSUE THREAD

**Issue by lyndmi** [google/bundletool#117]
**Is your feature request related to a problem? Please describe.**
Yes because you can't install APK normally anymore. You need 3rd party app 	
Split APKs Installer (SAI) to be able to install split APK but it's not working with some devices like MIUI or FlymeOS
This is the stupidest technology I ever seen in my life

**Describe the solution you'd like**
Be able to merge splitted APK to single APK without bundles

**Describe alternatives you've considered**
Extract or decompile files and put into base.apk. Compile and resign. It is complicated
Using Apkpure to download single APK

**Additional context**
Nothing

**Comment by kvafy** [comment]
You can run the build-apks command with `--mode=universal` to build an APK that contains your whole app (without modules that are explicitly excluded from fusing using the [dist:fusing attribute](https://developer.android.com/studio/projects/dynamic-delivery)).

**Comment by lyndmi** [comment]
But it ask me for bundle file which I don't have. Where to find it in split apk?

**Comment by kvafy** [comment]
Can you explain your use case in greater detail? What is your relation to the app, are you the owner?

**Comment by plecesne** [comment]
Note: You don't need a third-party tool to install APKs. `adb` (shipped as part of Android SDK Tools) supports the installation of split APKs as well through the command `install-multiple`.

**Comment by lyndmi** [comment]
No i'm not the owner of the app. I needed to install apps and games that is not compatible anymore due to app bundles but SAI is not working with my friends phone due to firmware issue
But thanks for the adb command though. My friends will be forced to bring laptop just to install split APKs.
Again this is the stupidest technology I ever seen that making the life harder.
Please come with solution with install split apk and merging apks without bundle file, we can't afford to buy compatible phones

**Comment by plecesne** [comment]
First of all, thank you for your feedback.
There is no easy way to merge split APKs once they have been generated and we have no current plan on adding support for it.

In the middle of all your generous feedback, I still fail to see the flow that is failing for you. Are you trying to sideload an app? Without a laptop? Where does the app come from then? I am not familiar with SAI, Apkpure or Apkcombo and we are not maintaining any of those, so you will have to contact the maintainers of those tools if they're not working for you.

**Comment by lyndmi** [comment]
Yes i'm trying to sideload an app. As said i'm getting split APK from 3rd party websites. Maintainers or developers of SAI can't do anything if the issue is from the firmware and app developers decided to switch to stupid bundle thing
If you won't add support merging APK then remove option to sideload APK entirely from Android 10!
We are considering to move to iOS due to Android being complicated

**Comment by megapro17** [comment]
On ios you can't even install app without external apps, and you call this not complicated?

**Comment by AndnixSH** [comment]
You can merge split APKs to one using SAP tool. It was created by release-apk.com but I reshared it on my website so anyone can download without registration with safe download links ;)
https://www.andnixsh.com/2020/06/sap-split-apks-packer-by-kirlif-windows.html

**Comment by Faizi-Apps** [comment]
> You can merge split APKs to one using SAP tool. It was created by release-apk.com but I reshared it on my website so anyone can download without registration with safe download links ;)
> https://www.andnixsh.com/2020/06/sap-split-apks-packer-by-kirlif-windows.html

THANKS

**Comment by wefalltomorrow** [comment]
> 
> 
> You can merge split APKs to one using SAP tool. It was created by release-apk.com but I reshared it on my website so anyone can download without registration with safe download links ;)
> https://www.andnixsh.com/2020/06/sap-split-apks-packer-by-kirlif-windows.html

@AndnixSH This is great, but you may want to add the latest version to your site :)

**Comment by AndnixSH** [comment]
@wefalltomorrow updated as requested

**Comment by AndnixSH** [comment]
Btw, you can use apkcombo.com to download single APK

Tutorial https://www.andnixsh.com/2019/08/how-to-download-single-apk-with-lib.html

**Comment by fzyzcjy** [comment]
> You can merge split APKs to one using SAP tool. It was created by release-apk.com but I reshared it on my website so anyone can download without registration with safe download links ;) https://www.andnixsh.com/2020/06/sap-split-apks-packer-by-kirlif-windows.html

Sounds promising! Unfortunately it seems not to be open sourced...

**Comment by AndnixSH** [comment]
Yeah, I needed command line too for my automation script. I have asked the author to provide it

**Comment by fzyzcjy** [comment]
@AndnixSH Does the author respond?

**Comment by AndnixSH** [comment]
> @AndnixSH Does the author respond?

Sorry for late reply.
Sadly no reply from him yet. Feel free to ask him too on this page https://forum.release-apk.com/viewtopic.php?t=99023

**Comment by KarmaMod** [comment]
> 
> Sorry for late reply. Sadly no reply from him yet. Feel free to ask him too on this page https://forum.release-apk.com/viewtopic.php?t=99023

He has a public email, I sent him email directly

**Comment by VanHoevenTR** [comment]
Any alternatives? really needed cmd for my scripting too

**Comment by muelli** [comment]
yeah, there should be non-interactive, headless solution.

**Comment by ax** [comment]
Take a look at https://github.com/ax/apk.sh.

**Comment by kikfox** [comment]
Check this tool: 

[https://github.com/REAndroid/APKEditor](https://github.com/REAndroid/APKEditor)

**Comment by adeii** [comment]
AntiSplit-X apk works when sometimes SAP 6.9.0 can not build APK till the end.
https://deedomk.itch.io/antisplit-x
You just have to pack all APKs to *.zip or *.apks

**Comment by nimaid** [comment]
In case anyone finds this like I did through Google, here is SAP 6.9.9, I made an account on the forum to get the latest version:
https://drive.google.com/file/d/1UnKr1SnX14RL_e9IpcpQhA6AnYwB0fjL/view?usp=sharing

**Comment by ax** [comment]
> In case anyone finds this like I did through Google, here is SAP 6.9.9, I made an account on the forum to get the latest version:
> https://drive.google.com/file/d/1UnKr1SnX14RL_e9IpcpQhA6AnYwB0fjL/view?usp=sharing

What about apk.sh?

**Comment by ajburley** [comment]
I'm looking into this today and I'm similarly disappointed that `bundletool` doesn't have this feature out of the box. I'm in a situation where I can't use `bundletool install-apks` or `adb install-multiple` because I'm using MDM solutions which require binaries to be uploaded in APK format.

Using `mode=universal` is also not really good, as it totally defeats the point of using AAB in the first place by putting everything into one APK.

Above mentioned APKEditor at https://github.com/REAndroid/APKEditor looks promising.
I was not able to figure out how to use [apk.sh](https://github.com/ax/apk.sh) referred to above to do this operation.

Here's another potential solution: https://github.com/LuigiVampa92/merge-apks
