### ISSUE TITLE
Force compress the native libraries in the .aab file built with Xamarin Android.

### ISSUE THREAD

**Issue by hanseul1795** [google/bundletool#119]
Related issue : .so files in the armv8-Apks are not compressed #118 

The reason why we want the native libraries to be compressed is because we are trying to hit the 150mb apk size limitation so we do not get the wifi needed prompt from the store.

I know that there is a way to ignore uncompressed native libraries with Gradle, but not with Xamarin Android. 

So, is there a way to force compress the native libs using the bundle tool for the API level above 28? 

Thank you

**Comment by plecesne** [comment]
The prompt in Play Store is based on the **download size**, not the actual raw file size, so again, you would be better off leaving the files uncompressed as this will result, in the worst case, in the same size, or in the best case, an actual smaller download size.

Now, that being said, to force the native libraries to remain compressed in the APKs (which will cause bigger download size and bigger size on device), you can configure this [in the BundleConfig](https://github.com/google/bundletool/blob/2e9ac4e628a690c0fce402548fe90c747c86533c/src/main/proto/config.proto#L39) that is passed to the [build-bundle command](https://github.com/google/bundletool/blob/5ac94cb61e949f135c50f6ce52bbb5f00e8e959f/src/main/java/com/android/tools/build/bundletool/commands/BuildBundleCommand.java#L110).

**Comment by hanseul1795** [comment]
@plecesne Thank you. I needed an answer from the bundletool team to make a reference in my report.
