### ISSUE TITLE
How to disable v2 signature

### ISSUE THREAD

**Issue by ljd1996** [google/bundletool#121]
How do I disable v2 signatures when I generate a series of apks using `bundletool build-apks`?

Further, when I upload the Android App bundle to Google play, Google will automatically sign my apk, how to disable v2 signature during this signature process?

Thank you.

**Comment by kvafy** [comment]
Currently the v2 signing cannot be manually disabled.

What is the motivation for doing so? The v2 signing scheme is superior to v1 as it delivers better on-device performance, as well as higher security guarantees.

**Comment by ljd1996** [comment]
Okay, I understand now, thank you!
