### ISSUE TITLE
Getting an Incorrect keystore password error

### ISSUE THREAD

**Issue by sajadj313** [google/bundletool#122]
**Describe the bug**
Throws an "Incorrect keystore password" when trying to execute build-apks command.

**Bundletool version(s) affected**
Version: 0.10.3

**Stacktrace**
```
[BT:0.10.3] Error: Incorrect keystore password.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Incorrect keystore password.
	at com.android.tools.build.bundletool.model.SigningConfiguration.extractFromKeystore(SigningConfiguration.java:116)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:449)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:409)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```

**To Reproduce**

- Should have a release key store
- release key store should have a password which contains special characters (*!@#$%^&)
- build a bundle file using the release key store
- use the bundle tool to build apks files using that bundle. the key store should be the same as the one which was used to build the bundle

**Expected behavior**
bundle tool should accept the same password that was used in the release key store file and should build the apks

**Known workaround**
If no key store info is specified, bundle tool will by default sign the apks using the debug key store.

**Environment:**
OS: macOS 10.14.6

**Additional context**
Getting different behaviors when providing the **--ks-pass** password with **pass:** prefix and with **file:** prefix. When supplying with **pass:** prefix, the terminal shows an error **-bash: !: event not found** (probably because of special characters). But when supplied with **file:** prefix, the password is read from file but it might have been modified internally which makes it unable to execute the command.

Tried surrounding both the **--ks-pass** and **--key-pass** parameters with double quotes but still the issue remains the same.

**Comment by plecesne** [comment]
Thank you for the feedback. It looks like a potential encoding issue, we'll look into it.

**Comment by sajadj313** [comment]
@plecesne waiting for a quick fix for this.. thank  you!

**Comment by plecesne** [comment]
I could not reproduce the issue.

```
$ echo '*!@#$%^&' > fakepwd.txt
$ bundletool build-apks --ks-pass file:fakepwd.txt --bundle app.aab --output app.apks --ks keystore-special.jks --ks-key-alias androiddebugkey --overwrite 
$ bundletool build-apks --ks-pass 'pass:*!@#$%^&' --bundle app.aab --output app.apks --ks keystore-special.jks --ks-key-alias androiddebugkey --overwrite 
```

Both worked for me. Try using single quotes so that the special characters are not interpreted.
If this still doesn't work for you, can you please reopen the bug and provide clearer steps on how to reproduce.

**Comment by sajadj313** [comment]
@plecesne the file prefix does not work but the single quotes trick worked for me. thank you! =D
