### ISSUE TITLE
Command unzip out.apks -d apks not working ?

### ISSUE THREAD

**Issue by Susith1995** [google/bundletool#124]
Error while parsing the flags: Syntax error: flags should start with -- (-d)
this error gives by the command.
OS: windows 10
Android Studio 3.5

**Comment by plecesne** [comment]
What command do you run exactly? 
The title suggests you're running the "unzip" command which is not a bundletool command, however the message you are getting is a bundletool error message, which is sort of confusing.

**Comment by Susith1995** [comment]
yes.i run the unzip command and i follow the below codelabs guide. anyway my intention was unzip  apks file.
https://codelabs.developers.google.com/codelabs/your-first-dynamic-app/index.html?index=..%2F..index#4

**Comment by plecesne** [comment]
Are you sure you're not running `bundletool unzip -d` instead of just `unzip -d`? That's the only explanation for getting a bundletool error message.

**Comment by Susith1995** [comment]
find a issue on using`unzip -d` command in windows environment. is there way to unzip  files(.apks) files in windows?

**Comment by plecesne** [comment]
I would recommend to search on Google or ask on stackoverflow for how to unzip on Windows. You can also change the extension of the file to `.zip`
