### ISSUE TITLE
How to share the split apks

### ISSUE THREAD

**Issue by ljd1996** [google/bundletool#125]
For a android app bundle application, how do I share apk with others, in other words, is there a way to merge multiple splits apk into one apk? Thank you!

**Comment by plecesne** [comment]
You can either share the *.apks file and have others use bundletool to sideload the app.
Or you can generate a universal standalone APK by using the flag `--mode=universal` in conjunction of the `build-apks` command. You can then extract the universal APK out of the *.apks file produced.

**Comment by ljd1996** [comment]
hank you for your answer. But now the problem is that when I installed the android app bundle application in my mobile, there are multiple split apks in the `/data/app/package/`. When I want to share it, how do I merge these apks into one in Java just like the app---ShareIt? I am not sure if this is a issue with bundletool.

**Comment by plecesne** [comment]
Can you clarify your intent? Is your goal to build an app to install these APKs programatically on another device? Or just extract them so they can be manually installed by someone else using `adb`? 
In other words, I'd like to understand why the fact that it's a single APK matters to you.

**Comment by ljd1996** [comment]
Sorry, I may not have expressed it clearly.
My goal is to build an application that programmatically merges these split apks into one and then share them with others so that they can install the application through the system's installer.Is there a way to do this?

**Comment by Ibuprophen** [comment]
@ljd1996, the following is the Repo for the SAI (Split APKs Installer) that performs what you're inquiring about. 

https://github.com/Aefyr/SAI

Enjoy! :-) 


~Ibuprophen

**Comment by ljd1996** [comment]
@Ibuprophen Thank you for your answer, but I have seen this project. It seems to be different from what I want to do. I want to merge several Split apks into one apk programmatically, and then share it with others to install. I found the [ShareIt](https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps&hl=zh) can merge these split apks, but I don't know how it is implemented.

**Comment by plecesne** [comment]
It would be extremely complicated to merge split APKs.
In particular, ShareIt does not do it: they use the [Play P2P API](https://android-developers.googleblog.com/2018/10/offline-p2p-installs-beta.html) to install all the split APKs through the Play Store whenever the APKs are verified by Play protect. Otherwise, they only install the base APK (and the app will crash on startup).

**Comment by ljd1996** [comment]
> It would be extremely complicated to merge split APKs.
> In particular, ShareIt does not do it: they use the [Play P2P API](https://android-developers.googleblog.com/2018/10/offline-p2p-installs-beta.html) to install all the split APKs through the Play Store whenever the APKs are verified by Play protect. Otherwise, they only install the base APK (and the app will crash on startup).

I tested it with ShareIt just now, it’s exactly what you said.
Thank you for your answer!

**Comment by AndnixSH** [comment]
Yeah merging split APKs is complicated
However there is a tutorial how to merge it manually if you are curious https://platinmods.com/threads/how-to-turn-a-split-apk-into-a-normal-non-split-apk.76683/
