### ISSUE TITLE
Can we use bundletool in our internal app store app?

### ISSUE THREAD

**Issue by jamieadkins95** [google/bundletool#129]
We would like to build a very small internal App Store app to help distribute builds to QA and our clients. Would it be possible to use bundletool to deliver bundles like the Play Store does?

How does the Play Store app / Play Store backend use bundletool internally? Does the app use bundletool to generate the device spec and send that to the backend to generate APKs? If so, could you point me at the relevant classes in bundletool to do that?

I had a look at 
https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/device/DeviceAnalyzer.java
but it requires an AdbServer instance to initialise. How do we generate a device spec on the device?

**Comment by plecesne** [comment]
Yes, you can try to replicate what Play is doing.

Play uses bundletool to generate the APKs, then reads the `toc.pb` file (proto of type `BuildApksResult`) which describes the targeting of the generated APKs. 

The device spec is pulled from the device through various Android APIs, but you can look at the `DeviceAnalyzer` class in bundletool which uses adb to build a DeviceSpec object. You should be able to find online all the Android APIs for how to fetch this information programatically.

Play servers then have their own serving logic to match a device with the right APK. The class `ApkMatcher` does a simplified version of this in bundletool which might be enough for your use-case. Play servers do something similar but handle more cases (e.g. various form factors, country restrictions, etc.).

**Comment by jamieadkins95** [comment]
Very useful info, thanks for your help!
