### ISSUE TITLE
bundletool "install-apks" prints "The APKs have been extracted..." without the app running on the Device

### ISSUE THREAD

**Issue by Ishanhonhaga** [google/bundletool#135]
**Describe the bug**
On Running the command 
_bundletool install-apks --apks=/Users/ishan/StudioProjects/Rz_Via_Lite/vialite/installed/build/outputs/bundle/debug/test_1.apks   --device-id=51078804_

Following message is displayed 
_The APKs have been extracted in the directory: /var/folders/8_/1wrwybwn55s2lvwyv05kkgf40000gp/T/1290905551054581147_

without the apk running on the device. 

**Bundletool version(s) affected**
Version: 0.11.0

**Screenshots**
Here are the screenshots of the executed commands
![Screenshot 2019-12-11 at 5 58 49 PM](https://user-images.githubusercontent.com/7644963/70621583-f066ae80-1c3f-11ea-9f49-159c4af53bdb.png)

Checked if the aab file was empty, but I could unzip it and see the apks.
![Screenshot 2019-12-11 at 6 01 20 PM](https://user-images.githubusercontent.com/7644963/70621737-42a7cf80-1c40-11ea-85bc-6086892ed3c9.png)

Since, no ks path is provided, according to the docs, 
 _bundletool attempts to sign your APKs with a debug key for you._
so I'm assuming the debug key to be consumed.

**Expected behavior**
Command runs, without any failure, and the App runs on the connected device.

**Environment:**
Android Device - One Plus 6
OS - Andorid 9

**Comment by plecesne** [comment]
The `install-apks` command only installs the app, it does not start it (mimicking the behaviour of `adb install`). You have to manually open the app once the app is installed on the device, this is working as intended.

**Comment by Ishanhonhaga** [comment]
Thank you for replying @plecesne 
The installed app was not showing up list of installed apps. 
Once the device was restarted, the app was available on the device.
