### ISSUE TITLE
 Error: Installation of the app failed.

### ISSUE THREAD

**Issue by wael120120** [google/bundletool#138]
Hello 
I generate the apks from bundle file but when I try to get apk it it is show this error
I used bundletool-all-0.12.0.jar

```
PS C:\Users\wael1\Desktop\RFID> java -jar bundletoolnew.jar  install-apks --apks=rfid.apks
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/Users/wael1/Desktop/RFID/bundletoolnew.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
The APKs have been extracted in the directory: C:\Users\wael1\AppData\Local\Temp\11897141535274759506
[BT:0.12.0] Error: Installation of the app failed.
com.android.tools.build.bundletool.model.exceptions.InstallationException: Installation of the app failed.
        at com.android.tools.build.bundletool.model.exceptions.InstallationException$Builder.build(InstallationException.java:47)
        at com.android.tools.build.bundletool.model.exceptions.InstallationException$Builder.build(InstallationException.java:41)
        at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:146)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$3(InstallApksCommand.java:195)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:79)
        at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:195)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: com.android.ddmlib.InstallException: Failed to establish session
        at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:70)
        at com.android.ddmlib.Device.installPackages(Device.java:928)
        at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:130)
        ... 6 more
PS C:\Users\wael1\Desktop\RFID>
```

> {
>   "supportedAbis": ["armeabi-v7a", "armeabi"],
>   "supportedLocales": ["en-GB"],
>   "deviceFeatures": ["reqGlEsVersion=0x30001", "android.hardware.audio.output", "android.hardware.bluetooth", "android.hardware.bluetooth_le", "android.hardware.camera", "android.hardware.camera.any", "android.hardware.camera.autofocus", "android.hardware.camera.flash", "android.hardware.camera.front", "android.hardware.faketouch", "android.hardware.location", "android.hardware.location.gps", "android.hardware.location.network", "android.hardware.microphone", "android.hardware.ram.normal", "android.hardware.screen.landscape", "android.hardware.screen.portrait", "android.hardware.sensor.accelerometer", "android.hardware.sensor.proximity", "android.hardware.telephony", "android.hardware.telephony.gsm", "android.hardware.touchscreen", "android.hardware.touchscreen.multitouch", "android.hardware.touchscreen.multitouch.distinct", "android.hardware.touchscreen.multitouch.jazzhand", "android.hardware.usb.accessory", "android.hardware.usb.host", "android.hardware.wifi", "android.hardware.wifi.direct", "android.software.activities_on_secondary_displays", "android.software.app_widgets", "android.software.autofill", "android.software.backup", "android.software.cant_save_state", "android.software.companion_device_setup", "android.software.connectionservice", "android.software.cts", "android.software.device_admin", "android.software.home_screen", "android.software.input_methods", "android.software.live_wallpaper", "android.software.managed_users", "android.software.midi", "android.software.picture_in_picture", "android.software.print", "android.software.sip", "android.software.sip.voip", "android.software.verified_boot", "android.software.voice_recognizers", "android.software.webview", "com.google.android.feature.TURBO_PRELOAD", "com.samsung.android.api.version.2402", "com.samsung.android.api.version.2403", "com.samsung.android.api.version.2501", "com.samsung.android.api.version.2502", "com.samsung.android.api.version.2601", "com.samsung.android.api.version.2701", "com.samsung.android.api.version.2801", "com.samsung.android.knox.knoxsdk", "com.samsung.android.sdk.camera.processor", "com.samsung.android.sdk.camera.processor.dof", "com.samsung.android.sdk.camera.processor.effect", "com.samsung.android.sdk.camera.processor.gif", "com.samsung.android.sdk.camera.processor.haze", "com.samsung.android.sdk.camera.processor.hdr", "com.samsung.android.sdk.camera.processor.lls", "com.samsung.feature.clockpack_v06", "com.samsung.feature.device_category_phone", "com.samsung.feature.device_category_phone_low_end", "com.samsung.feature.galaxyfinder_v7", "com.samsung.feature.ipsgeofence=1", "com.samsung.feature.samsung_experience_mobile", "com.sec.android.mdm", "com.sec.android.secimaging", "com.sec.feature.cover", "com.sec.feature.findo", "com.sec.feature.motionrecognition_service", "com.sec.feature.nsflp=350", "com.sec.feature.overlaymagnifier", "com.sec.feature.slocation=3"],
>   "glExtensions": ["GL_EXT_debug_marker", "GL_ARM_rgba8", "GL_ARM_mali_shader_binary", "GL_OES_depth24", "GL_OES_depth_texture", "GL_OES_depth_texture_cube_map", "GL_OES_packed_depth_stencil", "GL_OES_rgb8_rgba8", "GL_EXT_read_format_bgra", "GL_OES_compressed_paletted_texture", "GL_OES_compressed_ETC1_RGB8_texture", "GL_OES_standard_derivatives", "GL_OES_EGL_image", "GL_OES_EGL_image_external", "GL_OES_EGL_image_external_essl3", "GL_OES_EGL_sync", "GL_OES_texture_npot", "GL_OES_vertex_half_float", "GL_OES_required_internalformat", "GL_OES_vertex_array_object", "GL_OES_mapbuffer", "GL_EXT_texture_format_BGRA8888", "GL_EXT_texture_rg", "GL_EXT_texture_type_2_10_10_10_REV", "GL_OES_fbo_render_mipmap", "GL_OES_element_index_uint", "GL_EXT_shadow_samplers", "GL_OES_texture_compression_astc", "GL_KHR_texture_compression_astc_ldr", "GL_KHR_texture_compression_astc_hdr", "GL_KHR_texture_compression_astc_sliced_3d", "GL_KHR_debug", "GL_EXT_occlusion_query_boolean", "GL_EXT_disjoint_timer_query", "GL_EXT_blend_minmax", "GL_EXT_discard_framebuffer", "GL_OES_get_program_binary", "GL_OES_texture_3D", "GL_EXT_texture_storage", "GL_EXT_multisampled_render_to_texture", "GL_EXT_multisampled_render_to_texture2", "GL_OES_surfaceless_context", "GL_OES_texture_stencil8", "GL_EXT_shader_pixel_local_storage", "GL_ARM_shader_framebuffer_fetch", "GL_ARM_shader_framebuffer_fetch_depth_stencil", "GL_ARM_mali_program_binary", "GL_EXT_sRGB", "GL_EXT_sRGB_write_control", "GL_EXT_texture_sRGB_decode", "GL_EXT_texture_sRGB_R8", "GL_EXT_texture_sRGB_RG8", "GL_KHR_blend_equation_advanced", "GL_KHR_blend_equation_advanced_coherent", "GL_OES_texture_storage_multisample_2d_array", "GL_OES_shader_image_atomic", "GL_EXT_robustness", "GL_EXT_texture_border_clamp", "GL_OES_texture_border_clamp", "GL_EXT_texture_cube_map_array", "GL_OES_texture_cube_map_array", "GL_OES_sample_variables", "GL_OES_sample_shading", "GL_OES_shader_multisample_interpolation", "GL_EXT_shader_io_blocks", "GL_OES_shader_io_blocks", "GL_EXT_gpu_shader5", "GL_OES_gpu_shader5", "GL_EXT_texture_buffer", "GL_OES_texture_buffer", "GL_EXT_copy_image", "GL_OES_copy_image", "GL_EXT_shader_non_constant_global_initializers", "GL_KHR_robustness", "GL_KHR_robust_buffer_access_behavior", "GL_EXT_buffer_storage", "GL_EXT_external_buffer", "GL_EXT_EGL_image_array"],
>   "screenDensity": 280,
>   "sdkVersion": 28
> }

**Comment by plecesne** [comment]
Can you try installing an APK using `adb install app.apk` ? 
Then if it works, try to install APKs from the `.apks` file you generated using `adb install-multiple base-master.apk base-xxhdpi.apk base-armeabi-v7a.apk base-en.apk` (adjust the file names based on the name of the APKs that have been generated).
Let me know the result.

**Comment by wael120120** [comment]
@plecesne 
I tried to install another apk by adb it is doesn't work
```
PS C:\Users\wael1\Desktop\Flutter\sms orginal\sms-android2\sms-android\android\app\release> adb install skoobudy.apk
Performing Streamed Install
adb: failed to install skoobudy.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
PS C:\Users\wael1\Desktop\Flutter\sms orginal\sms-android2\sms-android\android\app\release>
```

**Comment by plecesne** [comment]
This thus does not look like an issue with bundletool. You may find more help on stackoverflow, e.g. [this post](https://stackoverflow.com/questions/13400499/is-there-any-way-to-ignore-install-failed-version-downgrade-on-application-insta).

**Comment by wael120120** [comment]
@plecesne 
Thanks the problem when I tried  to instaal apk because I was install previous apk
And adb now work 
```
PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release> adb install app-release.apk
Performing Streamed Install
Success
PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release>

```

**Comment by wael120120** [comment]
@plecesne 
adb install  work
adb install-multiple doesn't work
```

PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release> adb install app.apk
Performing Streamed Install
Success
PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release> adb install skoobudy.apk
Performing Streamed Install
adb: failed to install skoobudy.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release> adb install skoobudy.apk
Performing Streamed Install
Success
PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release> adb install-multiple app.apk skoobudy.apk
adb: failed to finalize session
Failure [INSTALL_FAILED_INVALID_APK: Split null was defined multiple times]
PS C:\Users\wael1\AndroidStudioProjects\sales\rfid\testgithub\build\app\outputs\apk\release>
```

**Comment by plecesne** [comment]
It doesn't look like the APKs you specified in the `install-multiple` command are actually split APKs. This command is not to install multiple apps at the same time, but to install multiple split APKs that are part of the same app, hence my recommendation to try this command with the split APKs extracted from the `.apks` file.

**Comment by ymakhno** [comment]
Hi @wael120120, is it still reproducible with the latest 0.14.0 version?
