### ISSUE TITLE
Android app Bundle On Demand don't work

### ISSUE THREAD

**Issue by DilerxD** [google/bundletool#14]
Hi, when i installed an app whit on demand feature, the app dont show the app the installation of the module, if is like the on demand feature doesn't work.
**I use this repository for example.**
https://github.com/googlesamples/android-dynamic-feature
**And this steps for make my apks**
https://developer.android.com/guide/app-bundle/test

Cheers.

**Comment by keyboardsurfer** [comment]
In order to make use of the capabilities of dynamic delivery you'll have to upload your bundle file to the Play Store. In a local installation all bundles are being installed on device in a single command.

**Comment by DilerxD** [comment]
Hi, @keyboardsurfer can i only install the base apk using bundletool ?

**Comment by plecesne** [comment]
Try passing the flag `--modules=base` to the `install-apks` command. The command help might have more details on this flag.
