### ISSUE TITLE
Support for APK patch size estimations

### ISSUE THREAD

**Issue by blundell** [google/bundletool#144]
**Is your feature request related to a problem? Please describe.**

I would like to calculate the patch size of an update from one .aab to another. This was done for singular APK's in another Google repository: 

https://medium.com/androiddevelopers/tracking-app-update-sizes-1a1f57634f7b
https://github.com/googlesamples/apk-patch-size-estimator

**Describe the solution you'd like**

apk-patch-size estimation built into BundleTool

**Describe alternatives you've considered**

The apk-patch-size tool being updated to support multi-apks. :-)

**Additional context**

:crossed_fingers: the Google teams can talk to each other (or already know each other!)
https://github.com/googlesamples/apk-patch-size-estimator/issues/6

**Comment by ymakhno** [comment]
Thank you for the feature request. We are looking into options how can we expose patch sizes to developers. 

Article and repository mentioned above are outdated, don't guarantee patch correctness and only produce very rough estimates. There is nothing we can include into bundletool at the moment.
