### ISSUE TITLE
 INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by rajnishmishra20** [google/bundletool#145]
**Describe the bug**
I opted in app singning from first apk upload on Google Play. Used the same .jks file to sign the .aab file generated before uploading to Google Play. Now used bundletool to generate .apks file while install using java -jar bundletool.jar install-apks --apks=singed_apk.apks , It says signature mismatch
I do not understand the incompatibility here.

**Bundletool version(s) affected**
Version: [e.g. 0.13.0]

**Stacktrace**
InstallException: Failed to finalize session : INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package xxx.xxxx.xxx signatures do not match the previously installed version; ignoring!
        at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:91)
        at com.android.ddmlib.Device.installPackages(Device.java:928)
        at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:129)
        ... 6 more

**Environment:**
OS: [e.g. Windoews 10]

**Additional context**
I do not understand while I used the same jks file to sign apk-bundle and .apks using bundletool how does it makes a signature mismatch

**Comment by plecesne** [comment]
I recommend you read a bit more about [App Signing by Play](https://support.google.com/googleplay/android-developer/answer/7384423).

This explains the difference between the **upload key** and the **signing key**. In short, the APKs that are served by Play to devices are not signed with the same key as the key you upload your App Bundle with.

Hopefully the link will answer all your questions.
