### ISSUE TITLE
Bundletool cannot package with "wrap.sh"

### ISSUE THREAD

**Issue by ganadist** [google/bundletool#149]
**Describe the bug**
I tried to add `wrap.sh` as described on https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh
But `bundletool` fails when `wrap.sh` is added.

**Bundletool version(s) affected**
Version: 0.13.3

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.
```
Caused by: com.android.tools.build.bundletool.model.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/lib/arm64-v8a/wrap.sh' uses reserved file or directory name 'lib'.
	at com.android.tools.build.bundletool.validation.BundleFilesValidator.validateModuleFile(BundleFilesValidator.java:116)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:81)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleModules$4(ValidatorRunner.java:64)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModules(ValidatorRunner.java:63)
	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:85)
	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:208)
```

**To Reproduce**
Source code is https://github.com/ganadist/VersionCodeDemo/tree/wrapsh_packaging.
Note: branch name is `wrapsh_packaging`

```
$ git clone https://github.com/ganadist/VersionCodeDemo -b wrapsh_packaging
$ ./gradlew :app:assembleDevelop
$ ./gradlew :app:bundleDevelop
```
There is no problem when perform `:app:assembleDebug` task, but when perform `:app:bundleDevelop` task, error will be raised.

**Expected behavior**
AppBundle created without any problem.

**Known workaround**

**Environment:**
OS: Archlinux
Android Gradle Plugin: 3.6.1

**Additional context**
[AGP 3.6.1 contains bundletool 0.10.3](https://android.googlesource.com/platform/tools/buildSrc/+/refs/heads/studio-master-dev/base/dependencies.properties#31), but, [sample project is using bundletool 0.13.3](https://github.com/ganadist/VersionCodeDemo/blob/wrapsh_packaging/build.gradle#L13)

**Comment by ymakhno** [comment]
Fixed in 0.14.0.

**Comment by zhaoshe** [comment]
@ymakhno is it possible to update bundletool independently and keep the agp version

**Comment by zhaoshe** [comment]
![image](https://user-images.githubusercontent.com/7018865/111135342-81e96c80-85b7-11eb-80f4-1828b434ced0.png)

**Comment by ymakhno** [comment]
In .aab file wrap.sh must be placed under `<module>/lib/<platform>` directory. `root/lib` is incorrect location.

**Comment by ymakhno** [comment]
It is Android Gradle Plugin issue in this case because `wrap.sh` should be placed in `<module>/lib/<platform>`. Please report to them http://issuetracker.google.com/issues?q=componentid:192709.

**Comment by troy-lamerton** [comment]
@zhaoshe did you find a workaround? I might make a pull request to fix this if there's no workaround

**Comment by troy-lamerton** [comment]
1. Add the follow code to your base module build.gradle file
2. Rename src/resources/lib to src/resources/_lib
3. Bundle will include your wrap.sh

```groovy
//#region workaround for bundletool not supporting wrap.sh
// Extract the aab, add wrap.sh and zip it back up.
// You must rename your src/resources/lib to src/resources/_lib so that bundletool ignores it. 
def baseModuleName = "launcher"
tasks.register('extractBundle', Copy) {
    group '_best'
    from zipTree("$buildDir/intermediates/intermediary_bundle/debug/$baseModuleName-debug.aab")
    into("$buildDir/rebundle")
}

tasks.register('includeWrapScript', Copy) {
    group '_best'
    // launcher\src\main\resources\_lib
    from "$projectDir/src/main/resources/_lib"
    into("$buildDir/rebundle/base/lib")

    mustRunAfter('extractBundle')
    dependsOn('extractBundle')
}

// run this task to make the app bundle with wrap.sh included
tasks.register('rebundleWithWrap', Zip) {
    group '_best'
    from "$buildDir/rebundle"
    archiveFileName = "$baseModuleName-debug.aab"
    destinationDirectory = file("$buildDir/intermediates/intermediary_bundle/debug")
    mustRunAfter('includeWrapScript')
    dependsOn('includeWrapScript')
}

afterEvaluate {
    tasks.getByName('packageDebugBundle').configure {
        finalizedBy(tasks.named('rebundleWithWrap'))
    }
}
//#endregion
```

**Comment by zhaoshe** [comment]
> @zhaoshe did you find a workaround? I might make a pull request to fix this if there's no workaround

I just forked this project, made some change and packaged a bundle.jar.
