### ISSUE TITLE
please add progress during the generate apks process

### ISSUE THREAD

**Issue by kosmasfn** [google/bundletool#150]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It's very inconvenient to have to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by plecesne** [comment]
> Describe the solution you'd like
> A clear and concise description of what you want to happen.

Could you be please more specific and fill the relevant sections of the template?

**Comment by ymakhno** [comment]
Closing as no description is provided.
