### ISSUE TITLE
Generate "universal" apk for specific config.

### ISSUE THREAD

**Issue by rossbacher** [google/bundletool#151]
**Is your feature request related to a problem? Please describe.**

I want to be able to generate a single "universal" apk that contains only the split APKs that I select via a device config and not all of them. 
e.g. I would want a universal APK with just the `arm64-v8a` ABI, or I want a "universal" apk with just xhdpi resources.

**Describe the solution you'd like**

Either the ability to allow `--connected-device` and `--device-spec` with subsets of that configurations e.g. (only abi)

**Describe alternatives you've considered**

Manually/Automatically merging a subset of split APKs.

**Additional context**

I understand that the PlayStore would never generate and serve such an apk but we would need to generate that APKs for different release channels and want to generate them form the same built Bundle and not build another binary.

**Comment by plecesne** [comment]
We call these APKs "standalone APKs" and we generated them for pre-L devices, but I presume that your app has `minSdkVersion` >= 21.

We don't support the generation of such APKs today for L+ devices but that's a feature we could consider adding in the future.

Note that we also accept [contributions](https://github.com/google/bundletool/blob/master/CONTRIBUTING.md) to bundletool if that's something you are keen on adding. Note that for such a change, we would need to review a short design first (to ensure that you are not wasting time coding something that we don't agree with).

**Comment by rossbacher** [comment]
I always thought that the pre-L devices would get the universal one. But yes, that is exactly what we would need. 

Yes, we are min >= 21 for our app, so we don't need that because the devices cannot install multiple apks but we want to generate "standalone" apks from the same bundle that we upload to the Play Store for different distribution channels.

We could do that by running another build but it is kinda useless as everything we need we could generate out of the bundle.

We were thinking about contributing that, let me follow up with the team on that.

**Comment by zhuyifan2013** [comment]
Hi @plecesne , I noticed that there was a flag `optimize-for` but deprecated now.  `optimize-for` is actually we want ( set standalone dimension ), but it is better to call it `standalone-dim` because it does not do other optimization. 

I guess you want people set optimization in BuildConfig file, but it is better to provide a way setting standalone dimension by bundletool command line tool. I provide a small trivial codes to show what we could do : https://github.com/zhuyifan2013/bundletool/pull/1

**Comment by plecesne** [comment]
Why would the BundleConfig dimensions not suffice?

One way to address your problem I think would be to add a `standalone` value for the flag `--mode` which would generate standalone APKs, regardless of `minSdkVersion` (but respecting the optimizations configured in the BundleConfig).

**Comment by zhuyifan2013** [comment]
@plecesne It seems that BundleConfig.json file could be set only when I am using `bundletool` to build application https://developer.android.com/studio/build/building-cmdline#build_your_app_bundle_using_bundletool. This  requires much more efforts to refactor the whole build process for us from gradle to bundle, which is not reasonable if I just need to generate a standalone with custom dimension form app bundle.

**Comment by plecesne** [comment]
I don't understand what refactor you have to do.

**Comment by ashughes** [comment]
@plecesne I was just looking for something similar and [discovered](https://github.com/google/bundletool/blob/8c3b87044bd114707bbcec70bcb407494f494a9c/src/main/java/com/android/tools/build/bundletool/commands/BuildApksCommand.java#L74) there are several options available for `--mode`, including `system`. In our case, we're trying to build an APK for a specific device configuration to be included in the system image, so this looks perfect.

However, I'm wondering how the proposed `--mode=standalone` would be any different than `--mode=system`?

**Comment by plecesne** [comment]
Great question.

Yes indeed, the `--mode=system` has been introduced for the system image purpose.

As for the differences:
* `--mode=standalone` would include the string for all languages, while `--mode=system` would include only the languages specified in the device spec (or all of them if you leave that field empty). In the latter case, Play Store will download the strings for languages defined in the system settings at the earliest opportunity, and developers using a custom language picker also have the possibility to download the needed languages manually using the Play Core SDK.
* Standalone APKs are meant to be deployed to pre-L devices, while System APKs are targeted for recent versions of Android, so there may be optimizations done on system APKs that are disabled for standalone APKs. One that comes to mind is native support for multidex, but there may be others.

**Comment by ashughes** [comment]
@plecesne Thanks for the detailed explanation. That makes sense.

I noticed there's also the option `SYSTEM_COMPRESSED` which says it
> generates compressed APK and an additional uncompressed stub APK (containing only android manifest) for the system image

Would you mind explaining when you would want this (as opposed to just `--mode=system`) for building an APK for a system image?

**Comment by plecesne** [comment]
This was an attempt at using a feature from the Android platform to put APKs on the system image compressed. However, there were some bugs in the feature and thus cannot be used as is. I would advise against using this option, we are likely to remove it from bundletool soon.

**Comment by huytu36** [comment]
I want to create an application to introduce my new web site. I used the site https://appsgeyser.com/ to create. However, it created a large 13.9 MB APK file that prevented me from posting it to Google Play to recommend it to everyone. A notice brought me to this software but I didn't know how to fix it. Can someone help me trim that APK file. Thank you!

**Comment by plecesne** [comment]
Hey @huytu36, thank you for your interest in bundletool. Unfortunately, this is not a help forum but an issue tracker. Try stackoverflow or other such forums for assistance.

**Comment by ymakhno** [comment]
Closing as solution is provided.
