### ISSUE TITLE
Cannot install unsigned APK from debug AAB

### ISSUE THREAD

**Issue by jam-cmesquita** [google/bundletool#153]
### Describe the bug
At the moment, we are trying to send to our QA team a debug AAB file and with the help of a script, which uses `bundletool`, they can extract and install from it an APK for a specific device.

The problem is that in order to generate the APKS and install the result, the `bundletool` force me to provide the `--ks` parameter.

**Is there not a way to generate unsigned (debug or release) APK from an (debug or release) AAB file?**

### Bundletool version(s) affected
Version: 0.13.4

### Stacktrace
```
>> bundletool build-apks --connected-device --bundle=$AAB_SOURCE_FILE_PATH --overwrite --output=$TEMP_APKS_PATH --adb=$ANDROID_ADB_HOME
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.

>> bundletool install-apks --apks=$TEMP_APKS_PATH
E/SplitApkInstaller: Failed to finalize session : INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl1240024415.tmp/0_base-xxhdpi has no certificates at entry AndroidManifest.xml
[BT:0.13.4] Error: Installation of the app failed.
com.android.tools.build.bundletool.model.exceptions.InstallationException: Installation of the app failed.
	at com.android.tools.build.bundletool.model.exceptions.InstallationException$Builder.build(InstallationException.java:47)
	at com.android.tools.build.bundletool.model.exceptions.InstallationException$Builder.build(InstallationException.java:41)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:145)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$3(InstallApksCommand.java:181)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:79)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:181)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl1240024415.tmp/0_base-xxhdpi has no certificates at entry AndroidManifest.xml
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:91)
	at com.android.ddmlib.Device.installPackages(Device.java:928)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:129)
	... 6 more
```

### To Reproduce

1. Generate a debug AAB file from Android Studio. 
2. Remove the `.android` directory under the `$HOME` directory
3. Run both commands in the _Stacktrace_ section and replace the `$AAB_SOURCE_FILE_PATH` with the debug AAB file of the first step.

### Expected behavior
I can install unsigned debug & release APKs from an AAB at any computer to any device type.

### Known workaround
????

### Environment:
OS: **macOS 10.13.6**

### Additional context
You have to take in consideration that this script (mentioned above) has to run on computers which doesn't have initially a `.android` folder.

**Comment by plecesne** [comment]
It's a requirement of the Android platform that all APKs must be signed to be installed on a device, so your requirement of _"installing unsigned APKs"_ is simply not possible.

> Is there not a way to generate unsigned (debug or release) APK from an (debug or release) AAB file?

When you delete the `.android` directory, the message from bundletool clearly says that _"The APKs won't be signed"_, so you've achieved that. Those APKs are simply not installable on any device per the security requirement of the Android platform.

Here are multiple options to handle QA (ordered by recommendation):

* Upload the AAB to [internal app sharing](https://support.google.com/googleplay/android-developer/answer/9303479?hl=en-GB) -- it's a very easy way to quickly upload AAB and get a link that you can share to your QA team to open from any device. There is no check on which key the AAB is signed with, nor any requirement on versionCodes (as opposed to other testing tracks), and the APKs are available almost immediately after upload.
* Upload the AAB to a closed [internal testing track](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en-GB) and add your QA team to the list of testers. They will receive exactly what your end-users will receive. Once the QA approves the build, you can simply promote this build to the production track and be sure that the exact same bytes would be delivered to your end users. On an internal testing track, the APKs are also available almost instantly after upload. On other tracks (open, closed), there can be a delay of a few hours.
* Generate the `.apks` yourself, and share with your QA the `.apks` file that contains signed APKs for all possible devices, then have them simply run the `install-apks` command with a connected device. Depending on your app, the `.apks` can be quite large.
* Share an AAB with your QA team and have them create a local keystore and have them generate signed APKs (which is the solution you were describing I believe).

Hope that helps.

**Comment by jam-cmesquita** [comment]
Thank you for the quick reply!

From all the alternatives the last 2 are the most suitable for me.
I have some questions though:

1. About the penultimate point: is the `--connected-device` flag compatible with `install-apks`? Otherwise I will need to use the `--device-spec` flag, right?
2. About the last point: how do I create a local keystore?
3. I found the `debug.keystore` under `.android` directory. Can I maybe reuse my `debug.keystore` in someone else computer? If not, how do I generate one?

Thank you in advance!

**Comment by plecesne** [comment]
1. `install-apks` uses the info from the connected device by default, hence the flag is unnecessary for that command.
1. There are many ways to create a keystore: from the command line using `keytool`, or using Android Studio. You'll find plenty of info on [Google](https://www.google.com/search?q=create+a+keystore).
1. You can reuse the same keystore on multiple computers, yes.

**Comment by jam-cmesquita** [comment]
Nice! That's really insightful and your answers helped me to my purpose.

Thanks a lot!

**Comment by DruxAMB** [comment]
> It's a requirement of the Android platform that all APKs must be signed to be installed on a device, so your requirement of _"installing unsigned APKs"_ is simply not possible.
> 
> > Is there not a way to generate unsigned (debug or release) APK from an (debug or release) AAB file?
> 
> When you delete the `.android` directory, the message from bundletool clearly says that _"The APKs won't be signed"_, so you've achieved that. Those APKs are simply not installable on any device per the security requirement of the Android platform.
> 
> Here are multiple options to handle QA (ordered by recommendation):
> 
> * Upload the AAB to [internal app sharing](https://support.google.com/googleplay/android-developer/answer/9303479?hl=en-GB) -- it's a very easy way to quickly upload AAB and get a link that you can share to your QA team to open from any device. There is no check on which key the AAB is signed with, nor any requirement on versionCodes (as opposed to other testing tracks), and the APKs are available almost immediately after upload.
> * Upload the AAB to a closed [internal testing track](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en-GB) and add your QA team to the list of testers. They will receive exactly what your end-users will receive. Once the QA approves the build, you can simply promote this build to the production track and be sure that the exact same bytes would be delivered to your end users. On an internal testing track, the APKs are also available almost instantly after upload. On other tracks (open, closed), there can be a delay of a few hours.
> * Generate the `.apks` yourself, and share with your QA the `.apks` file that contains signed APKs for all possible devices, then have them simply run the `install-apks` command with a connected device. Depending on your app, the `.apks` can be quite large.
> * Share an AAB with your QA team and have them create a local keystore and have them generate signed APKs (which is the solution you were describing I believe).
> 
> Hope that helps.



Thanks for the detailed explanation and references @plecesne 👩🏾‍💻👩🏾‍💻👩🏾‍💻👩🏾‍💻👩🏾‍💻

**Comment by DruxAMB** [comment]
> 1. `install-apks` uses the info from the connected device by default, hence the flag is unnecessary for that command.
> 2. There are many ways to create a keystore: from the command line using `keytool`, or using Android Studio. You'll find plenty of info on [Google](https://www.google.com/search?q=create+a+keystore).
> 3. You can reuse the same keystore on multiple computers, yes.

I created run a build command on my terminal and a keystore was generated for me by Expo ( React-native ), but I do not know where to get my password from. Can you please help with this?

**Comment by ForwardDeveloper** [comment]
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.

got this error when i convert abb file to apks file. Need guidance

**Comment by DruxAMB** [comment]
thanks, have been able to fix the bug
