### ISSUE TITLE
APKSet InstalledModules includes "base"

### ISSUE THREAD

**Issue by blundell** [google/bundletool#154]
**Describe the bug**
Not sure if this is a bundletool bug or a SplitInstall bug.

The `com.google.android.play.core.splitinstall.SplitInstallManager#getInstallModules` javadoc says that it exclude the "base" module. But after creating a universal APK with bundletool, it seems it does return the 'base' as one of the module Strings in the Set!

![image (8)](https://user-images.githubusercontent.com/655860/78980271-7bd04d80-7b15-11ea-873c-37401db4c17e.png)

**Bundletool version(s) affected**
Version: 0.13.4

**To Reproduce**

Have an app with dynamic modules that calls `getInstalledModules` and log out the result.
Run it before and after generating a Universal APK.

**Expected behavior**

"base" not to be included in the Set.

**Known workaround**

I do a `filter()` on the set to remove "base".

**Comment by plecesne** [comment]
Thank you for the report. It is likely to be a PlayCore issue, but we'll be coordinating with them when looking into it.

**Comment by ymakhno** [comment]
Fixed in Play Core.

**Comment by blundell** [comment]
Thanks, and confirmed for full closure: https://issuetracker.google.com/issues/153858938
