### ISSUE TITLE
Build-Apks have no dex-files after upgrading to gradle plugin version 4.0.0

### ISSUE THREAD

**Issue by Jitendra194** [google/bundletool#161]
I have a couple of dynamic feature modules in my project. When I updated  AGP to 4.0.0, I'm unable to install/test my app because of the following error I get when installing the apks using bundletool. 

`Module 'module1' has no dex files but the attribute 'hasCode' is not set to false in the AndroidManifest.xml.`

I've got minifyenabled set to true and proguard rules as well. It worked fine without issues on AGP 3.6.3.

**Comment by plecesne** [comment]
Do you have a sample project that can reproduce the issue?

**Comment by Jitendra194** [comment]
> Do you have a sample project that can reproduce the issue?

I just created another project which will be able to reproduce this issue. [https://github.com/Jitendra194/GradlePluginIssue](https://github.com/Jitendra194/GradlePluginIssue)

**Comment by ymakhno** [comment]
Thank you for providing the sample project. We will investigate and return back to you.

**Comment by ymakhno** [comment]
Your project uses very old version of R8 as you override it in your `build.gradle` to `classpath "com.android.tools:r8:1.6.84"` and AGP 4.0 is shipped with version 2.0.74 by default. If I remove this dependency from you build script the project builds successfully with and without additional proguard rules.

**Comment by Jitendra194** [comment]
> Your project uses very old version of R8 as you override it in your `build.gradle` to `classpath "com.android.tools:r8:1.6.84"` and AGP 4.0 is shipped with version 2.0.74 by default. If I remove this dependency from your build script the project builds successfully with and without additional proguard rules you provided in `proguard-rules.pro`.

Thank you. I didn't know R8 was bundled with gradle plugin by default.
