### ISSUE TITLE
Unable to upload instant app zip to play console

### ISSUE THREAD

**Issue by svshishkina** [google/bundletool#162]
Hello!
I am developing an instant app and have an issue with uploading to play console internal track. 
I successfully built bundle with **./gradlew bundleRelease** command, than generated apks with **bundletool** and launch instant app locally with **ia tool**.
But when I try upload apks.zip to play console I've got an error "The configuration APKs in your Instant App APKs should have targeting information."
What does mean this message? Can it be connected with bundletool? Or could you advise how correctly upload instant app apks.zip to play console?

**Comment by plecesne** [comment]
This is a question for the [Play Developer support](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en).
