### ISSUE TITLE
Bundletool exits with Error: null on extract-apks or install-apks command

### ISSUE THREAD

**Issue by Pato05** [google/bundletool#163]
**Describe the bug**
Basically, I try to extract a specific ABI APK from an APKs file with extract-apks or install it by install-apks, and it exits with Error: null
**Bundletool version(s) affected**
Version: [e.g. 0.3.3]
1.0.0 (latest, as of now)
**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.
```
[BT:1.0.0] Error: null
java.lang.NullPointerException
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:165)
        at com.google.common.io.ByteSource.read(ByteSource.java:286)
        at com.android.tools.build.bundletool.model.utils.ResultUtils.readTableOfContentFromApksArchive(ResultUtils.java:59)
        at com.android.tools.build.bundletool.model.utils.ResultUtils.readTableOfContents(ResultUtils.java:47)
        at com.android.tools.build.bundletool.commands.ExtractApksCommand.execute(ExtractApksCommand.java:168)
        at com.android.tools.build.bundletool.commands.ExtractApksCommand.execute(ExtractApksCommand.java:161)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:79)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)
```
**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.
Simply, get an APKs file and run `java -jar bundletool-all-1.0.0.jar extract-apks --apks=my_app.apks --device-spec=device.json --output-dir=apks/` or with the install-apks command `java -jar bundletool-all-1.0.0.jar install-apks --apks=my_app.apks`
**Expected behavior**
I'd expect to have the APK installed or the single APK file for my ABI extracted
**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: [e.g. iOS 10.3.3]
Windows 10 x64
**Additional context**
I got device.json file by using `java -jar bundletool-all-1.0.0.jar get-device-spec --output=device.json`

**Comment by plecesne** [comment]
It looks like your `.apks` file is missing the file `toc.pb`. 

I was unable to reproduce your issue with my `.apks` file.

**Comment by Pato05** [comment]
> It looks like your `.apks` file is missing the file `toc.pb`.
> 
> I was unable to reproduce your issue with my `.apks` file.

![image](https://user-images.githubusercontent.com/20874747/85566280-35788e00-b630-11ea-88ba-a9d12f5e517c.png)
It contains these files

**Comment by ymakhno** [comment]
Could you please share how have you built this apks file? Have you invoked `java -jar bundletool-all-1.0.0.jar build-apks`?

**Comment by Pato05** [comment]
> Could you please share how have you built this apks file? Have you invoked `java -jar bundletool-all-1.0.0.jar build-apks`?
No, I didn't, I've found that app online, they said to install through SAI

**Comment by plecesne** [comment]
This file was not generated by bundletool, so APKs cannot be extracted with bundletool.

**Comment by pesiik** [comment]
I have the same problem and I used bundletool. And this file was generated by bundletool.
