### ISSUE TITLE
Request: More verbose information about what is happening during build-apks and install-apks

### ISSUE THREAD

**Issue by johngoren** [google/bundletool#169]
**Is your feature request related to a problem? Please describe.**
Buildtool 1.0 is great but closed-lipped about printing to the screen what is doing. In the silence it is hard to understand what processes are happening, both for newcomers trying to get into the swing of Android Bundle and experienced users wondering how near we are to completion.

**Describe the solution you'd like**
A list of steps printed to the screen, a la Android Studio's build screen. And helpful cues for beginners explaining, e.g. "the app has been installed to the device" or "the split APKs set was successfully created in <name>.apks."

**Describe alternatives you've considered**
Have tried looking for --verbose settings.

**Additional context**
During **build-apks**, for example, the wait can be as long as 5-10 minutes but there might not be a word printed. Install-apks meanwhile provides only a single remark midway through that "The APKs have been extracted in the directory: /tmp/<...>," when really what you are more likely to be wondering is whether the installation finished successfully.

**Comment by ymakhno** [comment]
Fixed in 1.1.0.
