### ISSUE TITLE
Feature request: MissingSplitsManager translation for "Installation failed" dialog

### ISSUE THREAD

**Issue by user-mw** [google/bundletool#171]
**Is your feature request related to a problem? Please describe.**
The dialog, that appearing, when user installed application, using sideloading, should be not on english only. It is more convenient for **users**. As I noticed in **PlayCoreMissingSplitsActivity**, this is for english language only.

**Describe the solution you'd like**
I would like to see auto translation of text in Installation failed dialog (with resources maybe).

**Describe alternatives you've considered**
May be this feature is included to MissingSplitsManager, but I can't find it.

**Additional context**
If this request is in wrong place, then, please, provide me with additional useful links.

**Comment by ymakhno** [comment]
You feature request is related to Play Core, please use this issue tracker and component to request their support: https://issuetracker.google.com/issues?q=componentid:384531%20status:open.
