### ISSUE TITLE
Request: Dump application name

### ISSUE THREAD

**Issue by att55** [google/bundletool#173]
**Is your feature request related to a problem? Please describe.**

I want to get a application name of a aab file.
But bundletool (version 1.0.0) does not support this.

Bundletool can dump aab information from manifest.
As far as I know, most of AndroidManifests in the world are as below.

```
<application
  android:label="@string/app_name"
  ...
```  

Although bundletool can dump **the path** of android:label, can't dump the value of string/app_name.
 
**Describe the solution you'd like**

Bundletool supports dumping the value of `string/app_name`.

**Comment by plecesne** [comment]
You should be able to use:

```
bundletool dump resources --bundle bundle.aab --resource string/app_name --values
```

Would that work for you?

**Comment by att55** [comment]
@plecesne I really appreciate you! Work it for me 😄 
I will close this issue because resolved.
