### ISSUE TITLE
build-apks fails silently

### ISSUE THREAD

**Issue by ericntd** [google/bundletool#175]
**Describe the bug**
No error thrown, `.apks` file simply not generated
Here's the `.aab` file: [app.zip](https://github.com/google/bundletool/files/5025569/app.zip)
Here's the [source code](https://github.com/googlecodelabs/android-dynamic-features/archive/codelab_step2.zip)

**Bundletool version(s) affected**
Version: 1.0.0

**Stacktrace**
NA

**To Reproduce**
Run the following commands (Windows Terminal) for the above `.aab` file
```
.\bundletool-all-1.0.0.jar build-apks --bundle=yourpath\app.aab --output==yourpath\app.apks
```
Alternatively, you can re-generate the `.aab` file from the source code above

**Expected behavior**
`.apks` file to be generated or error message shown

**Known workaround**
NA
**Environment:**
Windows 10

**Additional context**
Play Console publication is delayed so this tool is very much appreciated, thank you 👍

**Comment by plecesne** [comment]
> No error thrown, .apks file simply got generated

I assume you mean it did _not_ get generated?

**Comment by plecesne** [comment]
Worked well for me with your .aab:

```
$ bundletool version
1.0.0

$ bundletool build-apks --bundle app.aab --output app.apks
WARNING: The APKs won't be signed and thus not installable unless you also pass a keystore via the flag --ks. See the command help for more information.

$ ll app.apks
-rw------- 1 me primarygroup 39406203 Aug  5 09:12 app.apks
```

**Comment by ericntd** [comment]
Works for me in macOS too so I'm satisfied. Thank you

**Comment by mattford** [comment]
For anyone finding it in future I found that in Windows calling:
`.\bundletool.jar` produced no output, however calling `java -jar .\bundletool.jar` worked correctly
