### ISSUE TITLE
build-apks is never ending and does not create apks

### ISSUE THREAD

**Issue by bhallionOhbibi** [google/bundletool#179]
**Describe the bug**
build-apks command never end the process and does not create any file.

**Bundletool version(s) affected**
Version: all-1.2.0

**Stacktrace**
No stacktrace. No message in the console.

**To Reproduce**
I started the command using this line:
java -jar bundletool-all-1.2.0.jar build-apks --bundle="D:\Documents\MyProject\build\outputs\bundle\debug\MyProject.aab" --output="D:\Documents\MyProject\build\outputs\bundle\debug\MyProject.apks" --ks="D:\Documents\MyProject\MyProject.keystore" --ks-pass=pass:"*******" --ks-key-alias="prod" --key-pass=pass:"******" --local-testing

**Expected behavior**
I expeted the tool to create apk files

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: Windows 10

**Comment by plecesne** [comment]
What is the size of the app bundle, and how many entries does it have?

Some things you can try:

* Add the `--verbose` flag and see if anything gets printed.
* Add the `--device-spec` flag with a valid device spec json file (see [here](https://developer.android.com/studio/command-line/bundletool#manually_create_json) for details) to see if anything gets generated even for one device.
* Add the flag `--max-threads=10` to see if that speeds anything up.

If none of this gives any result, would you be able to share the bundle that is causing issue so we can debug this more closely?

**Comment by bhallionOhbibi** [comment]
Hi !

Thanks for the quick reply.

The file MyProject.aab weight 360MB.

I tried with all 3 arguments and succesfuly created APKs.
The command was quite fast. (about a minute or two)

It looks like the `--device-spec` argument unblock the process. I tried running the command again without `--device-spec` it and it blocked again.

Is there any documentation on the arguments `--max-threads=10` and `--verbose` ?

Anyway, thanks for your help. I should be able to use the tool now :)

**Comment by plecesne** [comment]
The `help` command will provide you with the details of all the flags you can use with the `build-apks` command, their explanation and accepted values:
```
java -jar bundletool-all-1.2.0.jar help build-apks
```

The fact that `--device-spec` unblocks you seems to suggest that the size of the generated APKs for all devices is substantial, possibly reaching multiple gigabytes (by default, the `build-apks` command generates all APKs). We are working on some performance improvements, but this won't change the size of the output, thus the device-spec flag is probably your best solution for now (if you need to create APKs this locally).

**Comment by bhallionOhbibi** [comment]
The `--mode=universal` option also solve my issue.

An single apk that can be installed like any regular apk was exactly what I needed in the first place.
