### ISSUE TITLE
Discrepancy between serving compressed v/s uncompressed .so files

### ISSUE THREAD

**Issue by garg-ketki** [google/bundletool#185]
Is serving *compressed v/s uncompressed* .so files determinant of *available storage space on the device*? I generated the aab file having Twilio library with arm64-v8 abi supported. The library contributes **10.4 MB** to the app size for an uncompressed version whereas **3.9MB** for the compressed one. 

While adding the aab on the IAS track, I could see `REQUIRES_USER_CONFIRMATION` split install session status only for certain devices. As per android documentation, any split _>10MB in size_ should experience this status code. Is it fair to assume that native lib compression is decided at runtime and some devices are getting the compressed version of the library whereas the others the uncompressed version? 

**Below is the observed pattern:**
For the following set of devices, we haven't observed the `REQUIRES_USER_CONFIRMATION` status code:
1. Pixel 3XL (Android version : 10 with 55% internal storage used)
2. One plus 7T (Android version : 10 with 60% internal storage used)
3. Samsung S10 (Android version : 10 with 52% internal storage used)

Whereas for the same build link, we experienced `REQUIRES_USER_CONFIRMATION` status code for the below devices:
1. Galaxy S8 (Android version : 9 with 98% internal storage used)
2. Pixel 3XL (Android version : 11 with 93% internal storage used)

**Bundletool version(s) affected**
Version: 1.13.0

_Note: We are using the default installLocation for the app._

**Comment by ymakhno** [comment]
Native libraries compression depends mainly on SDK version and doesn't depend anyhow on available storage space.

Unfortunately, this is not a help forum but an issue tracker. Try stackoverflow or other such forums for assistance.

**Comment by ymakhno** [comment]
If you think there is an issue with session status I recommend to contact Play Core team: https://issuetracker.google.com/issues?q=componentid:384531.

**Comment by garg-ketki** [comment]
Thanks, @ymakhno for confirming the behavior of native libraries w.r.t bundletool. Created a follow-up issue for the Play core team.
