### ISSUE TITLE
[1.3.0] Dex files are being re-written even if only base module contains DEX code

### ISSUE THREAD

**Issue by benjaminRomano** [google/bundletool#186]
**Describe the bug**
Starting in Bundletool 1.3.0, DEX files will be re-written in standalone/universal APKs even if only the base module contains DEX code. This is problematic for us as we apply our own optimizations to DEX files for startup performance which get undone by the rewriting process.

The root cause is that [here](https://github.com/google/bundletool/compare/1.2.0...1.3.0#diff-6138cbb788f216a7191afebe76d280f05f302915b4d65c3f5fc2328bb2058bbfR267), the logic was changed to skip if there is only one DEX file _or_ there is only 1 module (base). Previously, the logic was to skip if only module had DEX code. 

In our case, we have three feature modules with none of them containing DEX code.

**Bundletool version(s) affected**
Version: 1.3.0+

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**
DEX files are not touched if only the base module has DEX code.

**Known workaround**
This cannot be worked around without code changes. 

**Additional context**
Ideally, the  logic [here](https://github.com/google/bundletool/compare/1.2.0...1.3.0#diff-6138cbb788f216a7191afebe76d280f05f302915b4d65c3f5fc2328bb2058bbfR267) could be updated to instead check that there is <= 1 modules with `hasCode = true` in their `AndroidManifest.xml`. 

Related to this, it may be good to check that `hasCode=true` for all modules with dex files. Right now, [this method](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/validation/DexFilesValidator.java#L84) only checks for `hasCode=false` when there are no DEX files.

**Comment by ymakhno** [comment]
Thank you for the report. This change was introduced in a response to another issue and can't be easily reverted.

If you want to skip dex merging for standalone and universal apks I think we can provide such option explicitly as currently we don't guarantee anything and this method is our internal implementation that we change from time to time. Could you share how do you build your bundle: 
 * via bundletool's build-bundle command?
 * Android Gradle Plugin?

**Comment by benjaminRomano** [comment]
Are you referring to this [original issue](https://partnerissuetracker.corp.google.com/issues/150332381)? 

In the case outlined in this issue, we only have DEX code within one module so no DEX rewriting should be necessary at all -- assuming that the DEX code already respects mainDexList requirements for the standalone use case. The DEX files should already be optimal and use as-is. 

In our build pipeline we use both AGP and bundletool `build-bundle` to generate our App Bundles. In this case, the app bundle with our own optimized DEX files is constructed using `build-bundle`.

**Comment by benjaminRomano** [comment]
Assuming this behavior is made configurable through a bundletool option, I'd want to make sure this is factored in when the Play Store generates standalone APKs for end-users.

**Comment by ymakhno** [comment]
We will provide such option in bundle config in the next bundletool release. And yes this option will be respected by Google Play.

**Comment by ymakhno** [comment]
Option to skip dex merging is provided in [BundleConfig](https://github.com/google/bundletool/blob/master/src/main/proto/config.proto#L106). You need to set `dex_merging_strategy` to `NEVER_MERGE`. Please note that change needs a week or two to be propagated to Google Play.
