### ISSUE TITLE
How to rebuild the .aab file after some resources changes from exiting .aab

### ISSUE THREAD

**Issue by prasannakumark** [google/bundletool#189]
I've generated the .aab file using the ./gradlew bundle command. Latter unzipped the .aab got resources and dex files. Now I want to change some version code in AndroidManifest.xml, some resource files, and again need to recompile the same .aab file.

In the case of .apk, we can achieve using APKTool(reverse engineering) this working perfectly.

Since we have to move from APK to AAB, I'm unable to rebuild after modification .aab file. Please give your pointers on how to do this using the bundle tool commands?.

Thanks in advance!!

**Comment by ymakhno** [comment]
Unfortunately we don't support patching commands in bundletool and don't have plans to support it.

I recommend you to have a look on product flavors feature of Android Gradle plugin that allows you to generate different modifications of your app: https://developer.android.com/studio/build/build-variants, that's probably what you are trying to achieve. 

If you need to make a couple of changes that doesn't affect a bundle structure you probably can:
 * unzip the bundle 
 * make changes 
 * zip it back (make sure no directory entries are created, if you use linux zip command-line tool `--no-dir-entries` flag) 
 * sign it with apksigner utility from Android SDK: `apksigner sign --ks yourkey.jks --min-sdk-version 18 repacked.aab`

**Comment by prasannakumark** [comment]
Thanks for the quick update. 
Till the third step, I've done the changes. 
Now from taking that zip file how to make the repacked.aab?

I've tried below the step to make repacked.aab

`java -jar bundletool-all-1.3.0.jar build-bundle --modules=repacked.zip --output=repacked.aab
`
**Getting the below error**

> [BT:1.3.0] Error: Module 'repacked' is missing mandatory file 'manifest/AndroidManifest.xml'.
> com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Module 'repacked' is missing mandatory file 'manifest/AndroidManifest.xml'.
> 	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
> 	at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.checkModuleHasAndroidManifest(MandatoryFilesPresenceValidator.java:85)
> 	at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.validateModuleZipFile(MandatoryFilesPresenceValidator.java:40)
> 	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateModuleZipFile$2(ValidatorRunner.java:53)
> 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
> 	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateModuleZipFile(ValidatorRunner.java:53)
> 	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:74)
> 	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:227)
> 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:71)
> 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:47)

but the manifest/AndroidManifest.xml file is present. 

Can you please provide any other pointers to solve this?

Thanks in advance!!

**Comment by prasannakumark** [comment]
Thanks for the quick response!!.

In order to make changes, the resources file in the form of **resouces.pb,** unable to read and write. Here just we wanted to edit the app_name in strings.xml.

are there any tools, which converting to values directory and reverse it back to .pb formate?

Or, can we do something using the bundle tool?

Thanks in advance😊
