### ISSUE TITLE
Release 1.4.0 misses .jar assets

### ISSUE THREAD

**Issue by vincentcastagna** [google/bundletool#194]
**Describe the bug**

The .jar is missing in assets, causing install bundle tool to fail being fetched from CI. 

**Bundletool version(s) affected**

Version: 1.4.0

![image](https://user-images.githubusercontent.com/15191066/99827577-d14aef00-2b27-11eb-887b-794b85fa0c6a.png)

@ymakhno 

Using this task => https://marketplace.visualstudio.com/items?itemName=DamienAicheh.bundletool-tasks

**Comment by ymakhno** [comment]
Uploaded, thank you!
