### ISSUE TITLE
How do i share the aab with testing team / others during testing cycle?

### ISSUE THREAD

**Issue by riyaz** [google/bundletool#20]
AAB format generated during build process is not testing cycle friendly , 

Expectation :

Way to share the bundle (maybe aab) to testing team so that they can install as per their respective phone config using bundletool

Issues :

1. Since apks file is too big (~700MB)  to share its not suitable for sharing
2. aab file is not suitable for sharing since bundletool does not accept aab as input
3. assume even if i share aab and ask testing team to convert it to apks and then to install it in device, to convert aab to apks we need keystore pass /  key pass which cannot be shared with everyone.

Workaround :

As of now I'm creating a signed universal apk and sharing it with the team for testing, however this is not the apk users are going to use

**Comment by plecesne** [comment]
We are working on adding a --deviceSpec flag to the build-apks command so you can generate an APK Set for a given device. This way, you will be able to generate multiple smaller APK Sets instead of one big one. That should hopefully address all you concerns.

**Comment by riyaz** [comment]
That's one step closer, still that will not solve origin problem.

Its better if testers use multiple devices and test multiple variations of
apk, so best would be to simulate the play store behavior through
bundletool.

Say, give aab itself to tester and they should be able to install device
specific apk using bundletool.

**Comment by plecesne** [comment]
I would recommend sharing the fat .apks in that case. Sharing the .aab is also possible, but as you noted, that will require them to also sign the APKs. If sharing the release keystore with them is not desirable, they can also use a debug keystore (that you could whitelist in the APIs that your app use, if necessary).

**Comment by riyaz** [comment]
Fat apk and debug keystore is the best workaround as of now.

**Comment by plecesne** [comment]
`--device-spec` flag now available in the `build-apks` command since 0.5.0, so smaller APK Sets can be created.
