### ISSUE TITLE
bundletool install .aab file can not run normal on Phone:Oppo Reno Ace

### ISSUE THREAD

**Issue by starlightjy** [google/bundletool#201]
My project use this split config in app module's build.gradle:
`bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }`
Only split for abi, the native library file(*.so)
after generate Signed Bundle 'app-release.aab', use bundletool1.4.0 install on my phones, most phone can run normal. But it can not run normal on One Phone: Oppo Reno Ace, I found it was installed without native library file (*.so). How can I  solve it? Help me

**Comment by ymakhno** [comment]
Could you please use `bundletool get-device-spec` command to get device spec of Oppo Reno Ace device and attach it here?

**Comment by starlightjy** [comment]
> Could you please use `bundletool get-device-spec` command to get device spec of Oppo Reno Ace device and attach it here?

[get-device-spec_with_oppo.zip](https://github.com/google/bundletool/files/6019418/get-device-spec_with_oppo.zip)

`{
  "supportedAbis": ["arm64-v8a", "armeabi-v7a", "armeabi"],
  "supportedLocales": ["zh-CN"],
  "deviceFeatures": ["reqGlEsVersion=0x30002", "android.hardware.audio.low_latency", "android.hardware.audio.output", "android.hardware.audio.pro", "android.hardware.biometrics.face", "android.hardware.bluetooth", "android.hardware.bluetooth_le", "android.hardware.camera", "android.hardware.camera.any", "android.hardware.camera.autofocus", "android.hardware.camera.capability.manual_post_processing", "android.hardware.camera.capability.manual_sensor", "android.hardware.camera.capability.raw", "android.hardware.camera.flash", "android.hardware.camera.front", "android.hardware.camera.level.full", "android.hardware.faketouch", "android.hardware.fingerprint", "android.hardware.location", "android.hardware.location.gps", "android.hardware.location.network", "android.hardware.microphone", "android.hardware.nfc", "android.hardware.nfc.any", "android.hardware.nfc.ese", "android.hardware.nfc.hce", "android.hardware.nfc.hcef", "android.hardware.nfc.uicc", "android.hardware.opengles.aep", "android.hardware.ram.normal", "android.hardware.screen.landscape", "android.hardware.screen.portrait", "android.hardware.sensor.accelerometer", "android.hardware.sensor.compass", "android.hardware.sensor.gyroscope", "android.hardware.sensor.light", "android.hardware.sensor.proximity", "android.hardware.sensor.stepcounter", "android.hardware.sensor.stepdetector", "android.hardware.telephony", "android.hardware.telephony.cdma", "android.hardware.telephony.gsm", "android.hardware.telephony.ims", "android.hardware.touchscreen", "android.hardware.touchscreen.multitouch", "android.hardware.touchscreen.multitouch.distinct", "android.hardware.touchscreen.multitouch.jazzhand", "android.hardware.usb.accessory", "android.hardware.usb.host", "android.hardware.vulkan.compute", "android.hardware.vulkan.level=1", "android.hardware.vulkan.version=4198400", "android.hardware.wifi", "android.hardware.wifi.aware", "android.hardware.wifi.direct", "android.software.activities_on_secondary_displays", "android.software.app_widgets", "android.software.autofill", "android.software.backup", "android.software.cant_save_state", "android.software.companion_device_setup", "android.software.connectionservice", "android.software.cts", "android.software.device_admin", "android.software.file_based_encryption", "android.software.home_screen", "android.software.input_methods", "android.software.ipsec_tunnels", "android.software.live_wallpaper", "android.software.managed_users", "android.software.midi", "android.software.picture_in_picture", "android.software.print", "android.software.secure_lock_screen", "android.software.securely_removes_users", "android.software.sip", "android.software.sip.voip", "android.software.verified_boot", "android.software.voice_recognizers", "android.software.webview", "android.sofware.nfc.beam", "cn.google.services", "coloros.gesture.range.pinning.support", "coloros.public.systemui.support_moregestureup", "com.google.android.feature.services_updater", "com.nxp.mifare", "com.oppo.feature.screen.heteromorphism", "oppo.Align.alarm.support", "oppo.all.client", "oppo.all.client_7_5", "oppo.all.client_lte_lte", "oppo.ams.act.freqcontrol", "oppo.ams.broadcast.adjust.obrecque", "oppo.ams.broadcast.adjust.pbrecque", "oppo.ams.broadcast.filter.power", "oppo.ams.broadcast.jumpqueue", "oppo.ams.broadcast.oppobt", "oppo.animation.round.support", "oppo.aod.support", "oppo.ap.sta.concurrency.support", "oppo.app2sd.disabled", "oppo.appdisable.support", "oppo.autobrightctl.animation.support", "oppo.autolight.psensor.notsupport", "oppo.battery.notify.new", "oppo.black.gesture.proximitysensor.support", "oppo.black.gesture.wake.up.arouse.support", "oppo.breeno.three.words.support", "oppo.brightness.mode.automatic", "oppo.childspace.support", "oppo.coloros.fake.bs", "oppo.common.gesture.follow.support", "oppo.common_center.bt.oppopods", "oppo.common_center.show.sceneservice.card", "oppo.common_center.wifi.qrcode_share", "oppo.common_center.wifi.smart_connect", "oppo.common_center.wlan.assistant", "oppo.contacts.support.card.recognize", "oppo.disable.small.window.leather", "oppo.display.colormode.support", "oppo.display.compat.support", "oppo.display.dcbacklight.support", "oppo.display.screen.gloablehbm.support", "oppo.display.screen.underlightsensor.support", "oppo.dm.privacy.disable.upload", "oppo.email.reset.password.support", "oppo.eyeprotect.support", "oppo.face.closeeye.detect", "oppo.feature.19111", "oppo.feature.19112", "oppo.feature.duplicate.permission.install", "oppo.feature.gamejoystick.support", "oppo.filtrated.app", "oppo.fingerprint.disable.dimlayer", "oppo.fulldiskencryption.unsupported", "oppo.gamespace.voicechange.support", "oppo.guard.elf.support", "oppo.hardware.arunit.support", "oppo.hardware.face.support", "oppo.hardware.fingerprint.optical.support", "oppo.high.brightness.support", "oppo.hotfix.support", "oppo.hw.manufacturer.qualcomm", "oppo.incomingcall.voicecontrol.shield", "oppo.inexact.alarm", "oppo.jobscheduler.support", "oppo.launcher.download.progress.support", "oppo.memory.auto.clean", "oppo.memory.auto.deep.clean", "oppo.multiapp.support", "oppo.multibits.dimming.support", "oppo.multimedia.dolby.effect.support", "oppo.multimedia.internal.record", "oppo.multimedia.record.channel.support", "oppo.multimedia.record.conflict", "oppo.multiuser.entry.unsupport", "oppo.network.tempdds.support", "oppo.ocloud.photo.sync", "oppo.otg.connection.menu.support", "oppo.ovs.smartmic.support", "oppo.package.encrypt.support.only", "oppo.performance.power.netwake", "oppo.phone.harass.intercept.off", "oppo.phone.show.number.mark", "oppo.proximity.need.delay", "oppo.proximity.tp.support", "oppo.proximity.under.lcd", "oppo.qualcomm.gemini.support", "oppo.remote.diagnosis.support", "oppo.roundcorner.support", "oppo.screen.hovering.support", "oppo.sdcard.storage.switch.support", "oppo.secrecy.support", "oppo.security.collect.support", "oppo.securitypay.support", "oppo.selfprotect.support", "oppo.sensor.fusionlight.support", "oppo.softsim.ignore_data_setting", "oppo.soundeffect.support", "oppo.stk.launcher", "oppo.support.single.partition", "oppo.sw.solution.device", "oppo.sw.solution.rom", "oppo.system.use_new_oppo_name", "oppo.talkback.guide.install.support", "oppo.tp.limit.support", "oppo.traffic.limit.support", "oppo.user.delete.channel.support", "oppo.wlan.dualsta.support", "oppo.wlan.privateDns.support", "oppo.wlan.sla.support"],
  "glExtensions": ["GL_OES_EGL_image", "GL_OES_EGL_image_external", "GL_OES_EGL_sync", "GL_OES_vertex_half_float", "GL_OES_framebuffer_object", "GL_OES_rgb8_rgba8", "GL_OES_compressed_ETC1_RGB8_texture", "GL_AMD_compressed_ATC_texture", "GL_KHR_texture_compression_astc_ldr", "GL_KHR_texture_compression_astc_hdr", "GL_OES_texture_compression_astc", "GL_OES_texture_npot", "GL_EXT_texture_filter_anisotropic", "GL_EXT_texture_format_BGRA8888", "GL_EXT_read_format_bgra", "GL_OES_texture_3D", "GL_EXT_color_buffer_float", "GL_EXT_color_buffer_half_float", "GL_QCOM_alpha_test", "GL_OES_depth24", "GL_OES_packed_depth_stencil", "GL_OES_depth_texture", "GL_OES_depth_texture_cube_map", "GL_EXT_sRGB", "GL_OES_texture_float", "GL_OES_texture_float_linear", "GL_OES_texture_half_float", "GL_OES_texture_half_float_linear", "GL_EXT_texture_type_2_10_10_10_REV", "GL_EXT_texture_sRGB_decode", "GL_EXT_texture_format_sRGB_override", "GL_OES_element_index_uint", "GL_EXT_copy_image", "GL_EXT_geometry_shader", "GL_EXT_tessellation_shader", "GL_OES_texture_stencil8", "GL_EXT_shader_io_blocks", "GL_OES_shader_image_atomic", "GL_OES_sample_variables", "GL_EXT_texture_border_clamp", "GL_EXT_EGL_image_external_wrap_modes", "GL_EXT_multisampled_render_to_texture", "GL_EXT_multisampled_render_to_texture2", "GL_OES_shader_multisample_interpolation", "GL_EXT_texture_cube_map_array", "GL_EXT_draw_buffers_indexed", "GL_EXT_gpu_shader5", "GL_EXT_robustness", "GL_EXT_texture_buffer", "GL_EXT_shader_framebuffer_fetch", "GL_ARM_shader_framebuffer_fetch_depth_stencil", "GL_OES_texture_storage_multisample_2d_array", "GL_OES_sample_shading", "GL_OES_get_program_binary", "GL_EXT_debug_label", "GL_KHR_blend_equation_advanced", "GL_KHR_blend_equation_advanced_coherent", "GL_QCOM_tiled_rendering", "GL_ANDROID_extension_pack_es31a", "GL_EXT_primitive_bounding_box", "GL_OES_standard_derivatives", "GL_OES_vertex_array_object", "GL_EXT_disjoint_timer_query", "GL_KHR_debug", "GL_EXT_YUV_target", "GL_EXT_sRGB_write_control", "GL_EXT_texture_norm16", "GL_EXT_discard_framebuffer", "GL_OES_surfaceless_context", "GL_OVR_multiview", "GL_OVR_multiview2", "GL_EXT_texture_sRGB_R8", "GL_KHR_no_error", "GL_EXT_debug_marker", "GL_OES_EGL_image_external_essl3", "GL_OVR_multiview_multisampled_render_to_texture", "GL_EXT_buffer_storage", "GL_EXT_external_buffer", "GL_EXT_blit_framebuffer_params", "GL_EXT_clip_cull_distance", "GL_EXT_protected_textures", "GL_EXT_shader_non_constant_global_initializers", "GL_QCOM_texture_foveated", "GL_QCOM_texture_foveated_subsampled_layout", "GL_QCOM_shader_framebuffer_fetch_noncoherent", "GL_QCOM_shader_framebuffer_fetch_rate", "GL_EXT_memory_object", "GL_EXT_memory_object_fd", "GL_EXT_EGL_image_array", "GL_NV_shader_noperspective_interpolation", "GL_KHR_robust_buffer_access_behavior", "GL_EXT_EGL_image_storage", "GL_EXT_blend_func_extended", "GL_EXT_clip_control", "GL_OES_texture_view", "GL_EXT_fragment_invocation_density", "GL_QCOM_validate_shader_binary", "GL_QCOM_YUV_texture_gather"],
  "screenDensity": 480,
  "sdkVersion": 29
}`

**Comment by ymakhno** [comment]
There is a bug in Oppo Reno firmware that doesn't allow to install splits via `adb install-multiple` command which bundletool uses under the hood. 

Oppo already fixed this bug in the latest firmwares which should be available on newer Oppo devices.

**Comment by zwy440** [comment]
Is Oppo a3 has the same bug？ My Oppo a3 also have so 。

**Comment by zwy440** [comment]
I have the latest progress，if I set abi enableSplit = fasle，it’s ok。The app run ok。
![image](https://user-images.githubusercontent.com/4748260/120431296-e217cf80-c3aa-11eb-82a5-79cd64c336b8.png)
The folder lib has arm64 and arm64 has my so files.
