### ISSUE TITLE
base module download size increases by 3MB when setting android:extractNativeLibs="false"

### ISSUE THREAD

**Issue by troy-lamerton** [google/bundletool#204]
**Describe the bug**

To reduce the size of app updates, I set `android:extractNativeLibs="false"` in our AndroidManifest.xml.
https://developer.android.com/topic/performance/reduce-apk-size.html#extract-false

Now when I check the download size of the base module, it grew by 3MB!

Dragging the output apks onto Android Studio (to inspect their contents) reveals almost zero differences between them - there is no obvious explanation for the +3MB size increase.

![studio64_2021-02-10_17-52-00](https://user-images.githubusercontent.com/13446008/107555144-1b97b580-6bd7-11eb-9ec4-b75f5bc5b9bb.png)

**Bundletool version(s) affected**
Version: 1.4.0

**Stacktrace**

With `android:extractNativeLibs` not set:

```sh
$ java -jar "bundletool-all-1.4.0.jar" build-apks --bundle=./extract_notset_ClashOfStreamers.aab --output=./extract_notset_ClashOfStreamers.apks
INFO: The APKs will be signed with the debug keystore found at 'C:\Users\G4G\.android\debug.keystore'.

$ java -jar "bundletool-all-1.4.0.jar" get-size total --apks=./extract_notset_ClashOfStreamers.apks --dimensions=ABI,TEXTURE_COMPRESSION_FORMAT --modules=base
ABI,TEXTURE_COMPRESSION_FORMAT,MIN,MAX
arm64-v8a,astc,86344143,86787370
```

With `android:extractNativeLibs="false"`:

```sh
$ java -jar "bundletool-all-1.4.0.jar" build-apks --bundle=./extract_false_ClashOfStreamers.aab --output=./extract_false_ClashOfStreamers.apks
INFO: The APKs will be signed with the debug keystore found at 'C:\Users\G4G\.android\debug.keystore'.

$ java -jar "bundletool-all-1.4.0.jar" get-size total --apks=./extract_false_ClashOfStreamers.apks --dimensions=ABI,TEXTURE_COMPRESSION_FORMAT --modules=base
ABI,TEXTURE_COMPRESSION_FORMAT,MIN,MAX
arm64-v8a,astc,90224239,90667477
```

**To Reproduce**

- I'm unable to share the aab files publicly, if they would be helpful, what email address can I send the download links to?
- Download the 2 aab files and run the bundletool commands from above.
- Observe that base module download size is 3MB larger

**Expected behavior**

Download size changes by a few KB when `android:extractNativeLibs="false"` is set in the manifest.

**Comment by ymakhno** [comment]
This optimisation (`android:extractNativeLibs=false`) forces native libraries to be stored in uncompressed format inside APK so Android platform is able to load such libraries from APK itself without extracting it on the local disk first. This decreases installation size of the application on device but APK itself becomes bigger.

Please note, that if you distribute your application through Google Play download size doesn't increase much because Play applies its own optimizations when serving APKs to devices.

**Comment by troy-lamerton** [comment]
@ymakhno yes, the APK itself is bigger - that is expected.

> Please note, that if you distribute your application through Google Play download size doesn't increase much because Play applies its own optimizations when serving APKs to devices.

How does Google Play determine download size? Isn't `bundletool get-size total` supposed to be an accurate estimate?

What I'm seeing is the download size reported by `bundletool get-size total` increase by 3MB when I set `android:extractNativeLibs=false`. The apk file itself becomes 100MB+ larger, which is fine. I hope we are on the same page now.

Where do these 3MB come from? There is no file in the output apk that accounts for it.

Repeating this in-case it was overlooked: I'm unable to share the aab files publicly, if they would be helpful, what email address can I send the download links to?

**Comment by ymakhno** [comment]
`bundletool get-size` command gives you size of APKs installed on device. When you enable uncompressed native libraries only size of ABI splits increase because libraries are not compressed anymore inside APK. In your example it looks like `base-arm64_v8a.apk` split is increased by 3MB.
