### ISSUE TITLE
Convert existing exported multiple apk files (for each architecture) to Android App Bundle

### ISSUE THREAD

**Issue by darcheville** [google/bundletool#210]
**Is your feature request related to a problem? Please describe. + Describe the solution you'd like**
I already have multiple exported apk files (for each architecture) and i would like to convert them to bundle 

Thanks and Regards

**Comment by ymakhno** [comment]
Bundletool is a tool designed to work with Android App Bundle format and allows to convert AAB file into the various APKs that are deployed to devices but not vice-versa. 

It is not always possible to convert APKs back to Android App Bundle and this is not the goal of bundletool, sorry.
