### ISSUE TITLE
null pointer exception for build-bundle command

### ISSUE THREAD

**Issue by johann50** [google/bundletool#214]
Getting null pointer exception for build-bundle  command
if the argument passed to --output is a file
in the same folder as where bundletool is being executed.

No problem if the argument is a path to a file in a folder.

Problem occurs in  BuildBundleCommand.java    line 260
because  outputDirectory is null and passed as argument to  Files.notExists
if output file has no parent.

**Comment by ymakhno** [comment]
Thank you for the report, we will include fix in the next release.

**Comment by ymakhno** [comment]
Fixed in 1.6.1.
