### ISSUE TITLE
build-bundle without further details

### ISSUE THREAD

**Issue by fsodic** [google/bundletool#219]
**Describe the bug**
the output just Error: null without any additional inform. And i was search article in Google but no related with my case

**Bundletool version(s) affected**
Version: 1.6.0

**Stacktrace**
```
Error: null
java.lang.NullPointerException
        at java.nio.file.Files.provider(Unknown Source)
        at java.nio.file.Files.notExists(Unknown Source)
        at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:260)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:72)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:48)
```

**To Reproduce**
```
java -jar bt.jar build-bundle --modules=zipfile.zip --output=bundle-out.aab
```

**Expected behavior**
I want to stick with the build with the command line without using android studio to make it easier. This is the last step (before signing) I've been looking for this whole year.

**Environment:**
OS: Windows 10 (19042.928).

**Additional context**

**Comment by ymakhno** [comment]
Fixed in 1.6.1.

**Comment by ymakhno** [comment]
General answer is yes, it supports uncompressed files. 

To investigate further please provide a sample project to reproduce the issue.

**Comment by fsodic** [comment]
Uploading 20210520-033859.mp4…

The sound still compressed 😊

**Comment by fsodic** [comment]
```
{
  "compression": {
    "uncompressedGlob": ["res/raw/**", "assets/**.uncompressed"]
  }
}
```

just add buildconfig
Now, finally i can build from command line ^_^
