### ISSUE TITLE
Make it easy to install app from aab binary

### ISSUE THREAD

**Issue by riyaz** [google/bundletool#22]
**Is your feature request related to a problem? Please describe.**

As of now installing app from aab is two or more steps, many usually use bundletool to install the app, so its better if we have single step to install the app from aab

We share aab to testing team for testing, they use different devices to test these, one of the simple workflow they follow is to install the aab to connected device however thats not a single step, so we are using a [wrapper script](https://gist.github.com/riyaz/b97d3a80858abd5c0f34a4ce1104ad3d) to do that.

**Describe the solution you'd like**

`bundletool install-aab <aab-path> --use-debug-certificate`

- remove intermediate step of converting aab -> apks
- use-debug-certificate or similar flags can be used to sign the apk on the fly using android debug keystore

**Describe alternatives you've considered**

[https://gist.github.com/riyaz/b97d3a80858abd5c0f34a4ce1104ad3d](https://gist.github.com/riyaz/b97d3a80858abd5c0f34a4ce1104ad3d)

As of now I'm using above wrapper script, it would be nice to have this inbuilt for testing purposes

**Comment by plecesne** [comment]
The main issue with integrating your feature request in bundletool is that different teams have different requirements. Some can sign locally with a debug key, some need to sign on a CI server with a protected key. Some share the bundle directly with your QA team while some prefer to share APK Sets to avoid re-generating APKs every time.

We wouldn't want to create a separate command for each use-case.

That being said, I agree that a few developers might be in a similar situation as yours and would benefit from a script like the one you've written, so one possibility would potentially be to publish as part of the GitHub repo one or more script templates that can be adapted by each developer grouping the commands as required for different use-cases. What do you think?

As for signing with the debug key by default, it's a good idea too. It's been suggested before and I think it's a good idea, we will look into it.

**Comment by ymakhno** [comment]
Closing as hung ticket. Signing with the debug key by default was implemented a long time ago.
