### ISSUE TITLE
> * [https://dl.google.com/android/maven2/com/android/tools/build/aapt2](https://dl.google.com/android/maven2/com/android/tools/build/aapt2/7.0.0-alpha14-7147631/aapt2-7.0.0-alpha14-7147631-linux.jar)

### ISSUE THREAD

**Issue by anppraveen** [google/bundletool#220]
> * [https://dl.google.com/android/maven2/com/android/tools/build/aapt2](https://dl.google.com/android/maven2/com/android/tools/build/aapt2/7.0.0-alpha14-7147631/aapt2-7.0.0-alpha14-7147631-linux.jar)

Hi,
Still not able to convert, Could you please try converting once.
Attached ab file for your reference.
[TrichromeChrome.zip](https://github.com/google/bundletool/files/6499039/TrichromeChrome.zip)

Thanks!!

_Originally posted by @anppraveen in https://github.com/google/bundletool/issues/211#issuecomment-842905580_

**Comment by ymakhno** [comment]
Aapt2 was upgraded in 1.7.0.
