### ISSUE TITLE
Test for size limit of aab

### ISSUE THREAD

**Issue by eyenie** [google/bundletool#222]
Hello,
Is there any way to write a test that checks size limit of aab, so Google Play Console can accept the aab.

We've tried next:
 Generate APKs:
           java -jar bundle_tool build-apks --overwrite --bundle=bundle_path --output=max_size_apks_path --device-spec=max_size_spec

 Get size:
            java -jar bundle_tool get-size total --apks max_size_apks_path

With next specs:
{
  "supportedAbis": ["x86_64"],
  "supportedLocales": ["en", "de", "es", "fr", "it", "ja", "ko", "ru", "zh", "zh-rCN", "zh-rHK", "zh-rSG", "zh-rTW"],
  "sdkVersion": 17,
  "screenDensity": 640
}

And then check if the size is less than 150 * 1024 * 1024. But it's seems incorrect +- 1Mb. Is there the correct way to write a test if Google Play Console will accept the aab?
.

**Comment by ymakhno** [comment]
In case attached spec really produces APK with the maximum size for your app this test should be fine. It might be a small difference between Play and bundletool but it should be matter of bytes and not megabytes.

If you have a sample project to reproduce this I can take a deeper look.
