### ISSUE TITLE
Modify app bundle contents like string.xml, app icons & AndroidManifest.xml and repackage it back to .aab

### ISSUE THREAD

**Issue by kgaurav23** [google/bundletool#223]
**Is your feature request related to a problem? Please describe.**
I am looking for a tool similar to what apktool used to do. I was using apktool to modify the apk contents(string resources, app icons & AndroidManifest.xml) to create a modified apk earlier and now I want to do same modifications for app bundle. 

**Describe the solution you'd like**
I would like bundletool to help me modify the contents of app bundles and repackage it back to modified app bundle.

**Describe alternatives you've considered**
I have tried modifying app bundle contents and repackage it back to app bundle. Getting below issue while building apk from modified app bundle:
bundletool build-apks --bundle=baseNew.aab --output=final.apks
INFO: The APKs will be signed with the debug keystore found at '/Users/kumarg/.android/debug.keystore'.
[BT:1.5.0] Error: The App Bundle zip file contains directory zip entry 'BUNDLE-METADATA/' which is not allowed.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: The App Bundle zip file contains directory zip entry 'BUNDLE-METADATA/' which is not allowed.

**Additional context**
In our CI/CD pipeline, we were using apktool to do these modifications earlier to create modified apk. Now as per new Google mandate for new apps publishing format, We need similar tool for app bundles as well. This is very urgent for us. Kindly work on this or suggest some alternative way to achieve the .aab modifications.

**Comment by ymakhno** [comment]
Unfortunately we don't support patching commands in bundletool and don't have plans to support it.

This question was already asked, here are responses that may help you:
 * https://stackoverflow.com/questions/64648900/how-to-rebuild-the-aab-file-after-some-resources-changes-from-exiting-aab
 *  #189
