### ISSUE TITLE
Can't generate apks from bundletool - PK: command not found

### ISSUE THREAD

**Issue by ductranit** [google/bundletool#224]
I have error command not found when run this command to generate apks
```
    bundletool.jar build-apks --bundle="app-release.aab" --output=app.apks 
```
It has the same error with release keystore 
```
bundletool build-apks --bundle=app-release.aab --output=app.apks
--ks=keystore.jks
--ks-pass=pass:mypass
--ks-key-alias=mykey
--key-pass=pass:mypass
```

**Bundletool version(s) affected**
Version: 1.70

**Stacktrace**
/Users/sa/bundletool.jar: line 1: PK: command not found
/Users/sa/bundletool.jar: line 2n5?R: command not found
/Users/sa/bundletool.jar: line 3: syntax error near unexpected token `)'
K-*??ϳR0?3???M???u?I,.?RH???K?K)??L?+???)?K*??I?y)9? ='03?i????PK'A-INF/MANIFEST.MF?M??LK-.?

**Environment:**
OS: macos 10.15.7

**Comment by ymakhno** [comment]
You should have java installed on your machine. Once you have it you can use:
```
java -jar bundletool.jar build-apks --bundle="app-release.aab" --output=app.apks 
```
