### ISSUE TITLE
required `--apks` flag not specified in the documentation

### ISSUE THREAD

**Issue by mcamou** [google/bundletool#234]
**Describe the bug**

I tried to extract the APKs from a bundle and got the following error:

```
$ java -jar ~/Downloads/sw/bundletool-all-1.7.1.jar extract-apks --bundle dist/bin/bundle.aab --output=dist/bin/apks --ks=keystore.jks
[BT:1.7.1] Error: Missing the required --apks flag.
```

The `--apks` flag is not mentioned in the documentation.

**Bundletool version(s) affected**
Version: 1.7.1

**Stacktrace**

```
$ java -jar ~/Downloads/sw/bundletool-all-1.7.1.jar extract-apks --bundle dist/bin/bundle.aab --output=dist/bin/apks --ks=keystore.jks
[BT:1.7.1] Error: Missing the required --apks flag.
com.android.tools.build.bundletool.flags.Flag$RequiredFlagNotSetException: Missing the required --apks flag.
        at com.android.tools.build.bundletool.flags.Flag.lambda$getRequiredValue$2(Flag.java:154)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.android.tools.build.bundletool.flags.Flag.getRequiredValue(Flag.java:154)
        at com.android.tools.build.bundletool.commands.ExtractApksCommand.fromFlags(ExtractApksCommand.java:152)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:81)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
```

**To Reproduce**

See above

**Expected behavior**

The documentation should mention the `--apks` flag and what to specify with it

**Known workaround**

None that I know of (short of perhaps trying out previous versions one by one until one works)

**Environment:**
OS: Ubuntu Linux 20.10

**Comment by ymakhno** [comment]
As I see apks flag is correctly specified in documentation: https://developer.android.com/studio/command-line/bundletool#extract_apks.

**Comment by ILoveLin** [comment]
I use this command to report an error message and you have been
                java -jar bundletool.jar install-apks app.apks


I have solved the problem with the ordered command now, you can try it.
            java -jar bundletool.jar  install-apks --apks=app.apks
