### ISSUE TITLE
Version[0.9.0]NullPointerException，but Version[1.8.0] is normal，Can I upgrade directly?

### ISSUE THREAD

**Issue by quincytann** [google/bundletool#239]
```
def taskCommand = ["java", "-jar", "$BUNDLE_TOOL_PATH", "build-apks",
                               "--bundle=$bundlePath",
                               "--output=$apksOutputPath",
                               "--ks=${RELEASE_KEYSTORE_FILE}",
                               "--ks-pass=pass:$RELEASE_KEYSTORE_PASSWD",
                               "--ks-key-alias=$RELEASE_KEYALIAS",
                               "--key-pass=pass:$RELEASE_KEY_PASSWD"]
            commandLine(taskCommand)

```

[BT:0.9.0] Error: null
16:11:37 java.lang.NullPointerException
16:11:37 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:11:37 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
16:11:37 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:11:37 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
16:11:37 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
16:11:37 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
16:11:37 	at com.android.tools.r8.utils.ThreadUtils.awaitFutures(ThreadUtils.java:21)
16:11:37 	at com.android.tools.r8.dex.ApplicationWriter.write(ApplicationWriter.java:177)
16:11:37 	at com.android.tools.r8.D8.run(D8.java:167)
16:11:37 	at com.android.tools.r8.D8.lambda$run$0(D8.java:71)
16:11:37 	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
16:11:37 	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
16:11:37 	at com.android.tools.r8.D8.run(D8.java:67)
16:11:37 	at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:70)
16:11:37 	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFiles(ModuleSplitsToShardMerger.java:333)
16:11:37 	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.lambda$mergeDexFilesAndCache$3(ModuleSplitsToShardMerger.java:300)
16:11:37 	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
16:11:37 	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFilesAndCache(ModuleSplitsToShardMerger.java:298)
16:11:37 	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeSingleShard(ModuleSplitsToShardMerger.java:192)
16:11:37 	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.merge(ModuleSplitsToShardMerger.java:106)
16:11:37 	at com.android.tools.build.bundletool.splitters.BundleSharder.shardBundle(BundleSharder.java:102)
16:11:37 	at com.android.tools.build.bundletool.splitters.ShardedApksGenerator.generateSplits(ShardedApksGenerator.java:68)
16:11:37 	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:200)
16:11:37 	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:486)
16:11:37 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
16:11:37 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
16:11:37 	Suppressed: java.util.concurrent.ExecutionException: java.lang.NullPointerException
16:11:37 		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
16:11:37 		... 20 more
16:11:37 	[CIRCULAR REFERENCE:java.lang.NullPointerException]
16:11:37 Caused by: java.lang.NullPointerException
16:11:37 	at com.android.tools.r8.dex.JumboStringRewriter.rewriteDebugInfoOffsets(JumboStringRewriter.java:236)
16:11:37 	at com.android.tools.r8.dex.JumboStringRewriter.rewrite(JumboStringRewriter.java:121)
16:11:37 	at com.android.tools.r8.graph.DexEncodedMethod.rewriteCodeWithJumboStrings(DexEncodedMethod.java:490)
16:11:37 	at com.android.tools.r8.dex.ApplicationWriter.lambda$rewriteCodeWithJumboStrings$3(ApplicationWriter.java:346)
16:11:37 	at com.android.tools.r8.graph.DexClass.forEachMethod(DexClass.java:123)
16:11:37 	at com.android.tools.r8.dex.ApplicationWriter.rewriteCodeWithJumboStrings(ApplicationWriter.java:346)
16:11:37 	at com.android.tools.r8.dex.ApplicationWriter.lambda$write$1(ApplicationWriter.java:170)
16:11:37 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
16:11:37 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
16:11:37 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
16:11:37 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
16:11:37 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
16:11:37 
16:11:37 > Task :shell:buildFakeApksForRelease FAILED

**Comment by ymakhno** [comment]
Could you please provide details for your request, what do you mean by upgrade directly? 

If you are asking about compatibility than yes, bundletool 1.8 and 0.9 are compatible.
