### ISSUE TITLE
Question about behavior of extract-apks subcommand with --device-spec flag

### ISSUE THREAD

**Issue by alapshin** [google/bundletool#24]
**Describe the bug**

I have an app that contains native libraries for multiple ABIs (armeabi-v7, arm64-v8a, x86)
and wanted to validate ABI-specific apks generated by `bundletool`. However only single ABI-specific apk is extracted from APK Set file

**Bundletool version(s) affected**
Gradle version: 4.9
Bundletool version: 0.5.0
Android Gradle plugin version: 3.2.0-beta04

**Stacktrace**
N/A

**To Reproduce**
1. Have following App Bundle config in `build.gradle`
```
    bundle {
        abi {
            enableSplit = true
        }
        density {
            enableSplit = false
        }
        language {
            enableSplit = false
        }
    }

```
2. Generate App Bundle via gradle `./gradlew bundleDebug`
3. Generate APK set archive using command
```
bundletool build-apks --bundle=/MyApp/my_app.aab --output=/MyApp/my_app.apks
```
4. Validate archive contents and see that `splits` directory contains files `base-master.apk`, `base-arm64_v8a.apk`, `base-armeabi_v7a.apk`, `base-x86.apk`
5. Extract apks from archive using command:
```
bundletool extract-apks --apks=/MyApp/my_app.apks --output-dir=/MyApp/apks/ --device-spec=spec.json
```
Where `spec.json` is
```
{
    "supportedAbis": ["armeabi", "armeabi-v7a", "arm64-v8a"],
    "sdkVersion": 27,
    "screenDensity": 420,
    "supportedLocales": ["en"]
}
```
6. As a result only `base-master.apk` and `base-armeabi_v7a.apk` are extracted but not `base-arm64_v8a.apk`
7. However if order of elements in `supportedAbis` is changed for example to
```
{
    "supportedAbis": ["armeabi", "arm64-v8a", "armeabi-v7a"],
    "sdkVersion": 27,
    "screenDensity": 420,
    "supportedLocales": ["en"]
}
```
Then `base-arm64_v8a.apk` is extracted but `base-armeabi_v7a.apk` is not.

**Expected behavior**
I assumed that `extract-apks` subcommand would extract all apks that match with conditions specified in json spec file. Is my assumption is incorrect and bundletool extracts only first matched apk?

**Known workaround**
By changing the order of elements in `supportedAbis` arrays I was able to extract apks for both `armeabi-v7a` and `arm64-v8a`.

**Environment:**
OS: Fedora 28 x86-64

**Additional context**
N/A

**Comment by plecesne** [comment]
The `extract-apks` command with `--device-spec` flag will extract the APK that should be served to that device by the store for the given device configuration.

The `supportedAbis` value of the DeviceSpec does not tell bundletool what libraries to include, but rather the preferred order of the ABIs supported by the device: bundletool thus selects the best ABI for the device based on the libraries available in the App Bundle.

I can't think of a good use-case to generate APKs with multiple ABIs since Android devices will eventually only load the native libraries for a _single_ ABI.

Note that I'm only talking about release APKs here. For testing purposes, the universal APK can be generated using the `--universal` flag (see the help of the `build-apks` command) and will contain all native libraries.

I hope that helps. Let me know if something is still unclear.

**Comment by alapshin** [comment]
>The supportedAbis value of the DeviceSpec does not tell bundletool what libraries to include, but rather the preferred order of the ABIs supported by the device: bundletool thus selects the best ABI for the device based on the libraries available in the App Bundle.

Thanks for clarification. I suspected that this might be the case but good to have confirmation.

> I can't think of a good use-case to generate APKs with multiple ABIs since Android devices will eventually only load the native libraries for a single ABI.

In my case I wanted to make sure that separate apks generated by `bundletool` are run correctly on test devices with different ABIs. So I thought `extract-apks` will produce `base-master.apk` and `base-armeabi_v7a.apk`, `base-arm64_v8a` etc. (for every abi from `supportedAbis`). I guess I was confused by previous experience with apk splits from android gradle plugin since they work  this way.
But this could be achieved by using different spec files.

> I hope that helps. Let me know if something is still unclear.

Yes, thanks again for quick response. I don't have any further questions.
