### ISSUE TITLE
Using ”---localtesting “ mode for overlay installation will result in plug-in legacy

### ISSUE THREAD

**Issue by FortuneDream** [google/bundletool#244]
**Describe the bug**
I have installed splitapk. Then I modified the code and tried to use the local testing mode to simulate and download the new splitapk. At this time, the plug-in has been downloaded. It is found that the modified code does not take effect because the legacy splitapk is still used at this time

**Bundletool version(s) affected**
Version: [1.8]

**Stacktrace**
build-apks --local-testing

**To Reproduce**
overlay installation

**Additional context**
Can you provide a good way to avoid this problem? For example, adding new parameters can delete the previous splitapk when the installation is overwritten?

**Comment by ymakhno** [comment]
Could you provide steps to reproduce for the problem?

**Comment by FortuneDream** [comment]
Yes.
First ：After installing the app, use the localtesting mode and call startinstall to install the module in the on-demand "module_ 1"

Second ： Modify the module_ 1. Use the localtesting mode again. 

Finally，If you overwrite the installation, the code will not take effect

**Comment by ymakhno** [comment]
Have you invoked install-apks after you modified module_1?

**Comment by FortuneDream** [comment]
yes.
I found that the root of the problem is that in the case of overwriting the installation and in the local testing mode, instead of calling SplitInstallmanager. getInstalledmodules (), I directly use Splitinstallmanager. getinstalledmodules (). This method will judge that the plug-in has been installed.

**Comment by ymakhno** [comment]
For now you can simply workaround this by:
`adb shell run-as $PACKAGE_NAME rm -rf /data/data/$PACKAGE_NAME/files/splitcompat && java -jar bundletool.jar install-apks ...`

where $PACKAGE_NAME is a package name of your app.

**Comment by ymakhno** [comment]
Fixed in 1.8.1.
