### ISSUE TITLE
Allow to provide custom ADB args

### ISSUE THREAD

**Issue by mykola-mokhnach** [google/bundletool#247]
**Is your feature request related to a problem? Please describe.**
Currently for an adb-related command, like install-apks or get-device-spec, it is not possible to provide specific adb arguments, like for example `-H` and `-P`, which makes it impossible to install an apks file to a remote device/get remote device spec or if the server is running on a non-default port

**Describe the solution you'd like**
Provide a possibility for bundletool to provide custom adb command line arguments

**Describe alternatives you've considered**
Unfortunately I currently don't see any alternatives. As of version 1.8.0 the tool only allows to set very limited amount of adb arguments.

**Additional context**
None

**Comment by ymakhno** [comment]
Yes, this is known issue, bundletool unfortunately doesn't support remote hosts at the moment you may find details here: #90.

Although I have to mention that non-default port is supported via ANDROID_ADB_SERVER_PORT env variable. 

We don't have a goal to have flag parity with adb, you are free to use vanilla adb in conjunction with `extract-apks` if your use case requires this.

**Comment by mykola-mokhnach** [comment]
Thanks for the advice. I think we could use these env variables for our scenario

**Comment by mykola-mokhnach** [comment]
I did check the [corresponding sources](https://github.com/google/bundletool/blob/950c8d63e62086e7db67620acdb114d2538e6d21/src/main/java/com/android/tools/build/bundletool/device/DdmlibAdbServer.java#L85) and I have one more question. @ymakhno could you please confirm that `ANDROID_ADB_SERVER_HOST` env variable is respected the same way it is done for `ANDROID_ADB_SERVER_PORT`?

**Comment by ymakhno** [comment]
No, only custom port is supported by bundletool at the moment. #90 is still open for host + port support.

**Comment by mykola-mokhnach** [comment]
Thanks. Do you accept contributions to this project? If yes then could I read some documentation for starters on how to prepare a local dev env?
