### ISSUE TITLE
Please provide CLI support for providing a Proguard map file

### ISSUE THREAD

**Issue by BenHenning** [google/bundletool#251]
**Is your feature request related to a problem? Please describe.**
I built a temporary stop-gap solution for building app bundles in Bazel until the Bazel team finishes their Android rules Starlark migration (see https://github.com/oppia/oppia-android/blob/b1cf2d4d380a007d94883df48d62794fc04950a3/oppia_android_application.bzl#L230). As part of this, I wanted to mimic AGP's embedding of an obfuscation proguard.map file since it makes archiving the .map file easier, and it's nice that the Play Store automatically extracts the map file from the AAB when uploaded.

Unfortunately, it seems like there's no way to do this from the CLI or directory structure support to do this. https://github.com/google/bundletool/blob/5ba6c056ac58318e1ffe0d2e3a7c5c9f1b34528c/src/main/java/com/android/tools/build/bundletool/commands/BuildBundleCommand.java#L141 is the method called directly from AGP to add the Proguard map file. However, when trying to build the AAB manually using build-bundle, there's no argument for passing the Proguard map file. Further, trying to add the BUNDLE-METADATA directly to a module bundle results in an error:

```
[BT:1.8.0] Error: Module files can be only in pre-defined directories, but found 'BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map'.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: Module files can be only in pre-defined directories, but found 'BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map'
```

I've also tried adding the BUNDLE-METADATA folder directly to the final AAB. While this builds without an issue (since it's just a zip file change in the end), it results in a failure when trying to install the APK:

```
[BT:1.8.0] Error: Only files directly in the dex directory are supported but found: dex.
java.lang.IllegalArgumentException: Only files directly in the dex directory are supported but found: dex.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.android.tools.build.bundletool.io.ApkSerializerHelper.toApkEntryPath(ApkSerializerHelper.java:62)
	at com.android.tools.build.bundletool.preprocessors.AppBundleRecompressor$CompressionManager.getCompressionLevel(AppBundleRecompressor.java:199)
	at com.android.tools.build.bundletool.preprocessors.AppBundleRecompressor.recompressAppBundle(AppBundleRecompressor.java:104)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:671)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:77)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
````

(Which is particularly unexpected since that error has nothing to do with the metadata directory).

**Describe the solution you'd like**
bundletool should provide a way for non-Gradle build systems to provide a proguard.map file & other bundle metadata. My preferred approach would be to allow module AABs to include bundle metadata that then gets merged into the final app bundle (which would probably have some correspondence to the existing merging work that happens when generating the APKs list from an AAB).

If that's not feasible then providing a proguard.map file directly to the command line for build-bundle would be a reasonable alternative.

**Describe alternatives you've considered**
See above.

Given the current limitation of the tool, I'll probably need to build my own Java-based script that hooks into bundletool directly as a dependency (like AGP does) to work around this issue.

**Additional context**
I kept most of the context above. However, my team's issue that's tracking this work is found here: https://github.com/oppia/oppia-android/issues/3962 (not much interesting context there as of the time I wrote up this issue).

**Comment by ymakhno** [comment]
You can use `--metadata-file` flag which is available for `build-bundle` command. For proguard mappings it should look like: `--metadata-file=com.android.tools.build.obfuscation/proguard.map:/path/on/disk/proguard.map`.
