### ISSUE TITLE
LocalTesting Mode ：Cleanup space appears :Split Install Error(-5): Split Install API is not available

### ISSUE THREAD

**Issue by FortuneDream** [google/bundletool#254]
**Describe the bug**
After I built and installed the module using localtesting, I cleaned up the storage space of the app. Open the app again and call to download the dynamicfeature, and split install error (- 5) will appear: split install API is not available. Is there any solution?

**Bundletool version(s) affected**
Version: [1.8.1]

**Comment by ymakhno** [comment]
I would recommend to uninstall and re-install the app via `bundletool install-apks`.

**Comment by FortuneDream** [comment]
Indeed, this problem will not occur after uninstallation. But our testers often reset the application by clearing the application space to quickly verify some problems. Would you like to ask if this bug can be repaired?

**Comment by ymakhno** [comment]
With local testing mode all not installed splits are stored inside app storage so when you clear it all splits are removed too. This is by design.

I may recommend to use [internal app sharing](https://play.google.com/console/about/internalappsharing/), if you don't want to rely on splits availability in app storage.

**Comment by FortuneDream** [comment]
> With local testing mode all not installed splits are stored inside app storage so when you clear it all splits are removed too. This is by design.
> 
> I may recommend to use [internal app sharing](https://play.google.com/console/about/internalappsharing/), if you don't want to rely on splits availability in local storage.

OK thanks。
