### ISSUE TITLE
Unity Build .aab Problem. 

### ISSUE THREAD

**Issue by PhoneHaHe** [google/bundletool#258]
**Describe the bug**
//: My Unity Project Use only debug keystore when build .aab file. It not use signed keystore. Unity give me a one error

**Bundletool version(s) affected**
Version: [e.g. 0.3.3]
Android SDK Ver. 11, Android Build Tool ver 30.0.3 

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.

System.Exception: Failed to run bundletool. Output: INFO: The APKs will be signed with the debug keystore found at 'C:\Users\basbo.android\debug.keystore'. [BT:1.6.0] Error: com.google.common.base.VerifyException java.lang.RuntimeException: com.google.common.base.VerifyException

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**

Unity Ver.2019.4.29f1
Gradle 5.6.4 

**Additional context**

"I build project mobile game unity on my pc and notebook. it get a old error about using debug keystore to signed in .aab. I already create keystore to use to publish game. But On My Team device not got the error any thing."

If you can answers about this problem. I will very thankfully.

**Comment by ymakhno** [comment]
It is not enough information to investigate the problem.
