### ISSUE TITLE
adb: failed to install app.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse base.apk: AndroidManifest.xml

### ISSUE THREAD

**Issue by mtrakal** [google/bundletool#259]
**Describe the bug**
call
`java -jar bundletool.jar build-apks --bundle=app-production-release.aab --output=app.apk --mode=universal`

after try to install
```
adb -e install -r app.apk
adb: failed to install app.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl962997621.tmp/base.apk: AndroidManifest.xml
```

**Bundletool version(s) affected**
bundletool-all-1.8.2.jar

**Environment:**
Android Studio Bumblebee | 2021.1.1 Beta 5
Build #AI-211.7628.21.2111.7956428, built on November 30, 2021
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, analyze.exceptions.on.the.fly=true, external.system.auto.import.disabled=true, search.everywhere.settings=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: CheckStyle-IDEA (5.59.0), String Manipulation (8.23.203.000.0), com.jetbrains.CyanTheme (1.2), com.jetbrains.grayTheme (1.2), com.materkey.codepoints (1.0.2), detekt (1.19.0), fr.dco.kotlin.vcs-kotlin-converter (1.2), net.avenwu.tools.biu (0.2.0), org.intellij.RegexpTester (1.0.8), mobi.hsz.idea.gitignore (4.1.0), wu.seal.tool.jsontokotlin (3.7.2), com.vladsch.idea.multimarkdown (3.0.202.112), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.6.0-release-798-AS7442.40), com.developerphil.adbidea (1.6.4), com.google.mad-scorecard (1.2), com.nbadal.ktlint (0.8.1), com.nvinayshetty.DTOnator (V0.997), gherkin (211.6693.111), net.lagerwey.cucumber-kotlin (2021.1.2), io.nimbly.tzatziki (10.0.0)

**Additional context**
The same AAB is valid when uploaded to Google Play and app is able to install from GP.

**Comment by ymakhno** [comment]
`build-apks` command produces APK Set file. Target universal APK is inside this archive. If you want to produce APK file instead you may try `--output-format=directory`.

**Comment by Abelhero** [comment]
does not work

**Comment by Abelhero** [comment]
hg
