### ISSUE TITLE
build a single apk (not ".apks") but is splitted by abi from aab?

### ISSUE THREAD

**Issue by fzyzcjy** [google/bundletool#260]
Originally I use build variants to build two apks: `myapp-armv7.apk` and `myapp-arm64.apk`, for the 32bit and 64bit architectures, respectively. For example, the 32bit apk only contains native `.so` files for 32bit, while the 64bit apk only contains those for 64bit.

However, now I not only want these two apk files, but also want a `myapp.aab` bundle. The question is, how to build the 32bit and 64bit apk from this aab bundle? 

I have tried https://stackoverflow.com/questions/53040047/generate-apk-file-from-aab-file-android-app-bundle . However, if I use `--mode=universal`, though I get an installable apk file, it contains both 32bit and 64bit `.so` files inside it, so it is really huge and we should not use it. If I do not use that flag, I get a bunch of apk files (i.e. an `.apks` file), but of course a user should only download one `.apk` file and click "install", so that is also not feasible.

related https://stackoverflow.com/questions/70538440/how-to-build-a-single-apk-not-apks-but-is-splitted-by-abi-from-aab

**Comment by fzyzcjy** [comment]
@ymakhno Hi is there any updates or replies?

**Comment by ymakhno** [comment]
We do not plan to support sharded APKs generation in bundletool.

You may try `--mode=system` with device spec (like `--device-spec=device.json`) which might allow you to achieve something similar. Although it is designed to generate APKs that can be preinstalled on Android devices.

Schema for device.json is here: https://github.com/google/bundletool/blob/master/src/main/proto/devices.proto#L9.
Example:
```
{
   "supportedAbis": ["armeabi-v7a"],
   "screenDensity": 240
}
```
