### ISSUE TITLE
Use adb in path by default

### ISSUE THREAD

**Issue by meizon** [google/bundletool#27]
**Describe the bug**
`adb` must be passed to bundletool, is it possible that it could use the adb executable in my path.

**Bundletool version(s) affected**
Version: 0.6.0

**Stacktrace**
[BT:0.6.0] Error: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.

**To Reproduce**
Use bundletool without providing an `adb`

**Expected behavior**
It would default to the `adb` on my path

**Environment:**
OS: Linux

**Comment by plecesne** [comment]
Could you set the environment variable ANDROID_HOME with the path to the SDK? Then, bundletool would be able to find `adb` in it.

**Comment by nfischer** [comment]
@plecesne it's common for our team (WebView and Chrome for Android) to use the `adb` binary in the `$PATH` (e.g., `sudo apt-get install adb`).

**Comment by nfischer** [comment]
@plecesne would you be open to a pull request for this feature?

**Comment by plecesne** [comment]
Absolutely, we welcome contributions.

**Comment by AdamSHurwitz** [comment]
How would one use adb in their path?

For instance, I'm attempting to use Android's **bundletool**.

`
bundletool-all-0.6.0.jar build-apks --bundle=/path/app.aab --output=/path/app.apks --ks=/path/coinverse-release.jks --ks-pass=file:/path/keyname.pwd --ks-key-alias="appname-release" --key-pass=file:/path/keystores/key.pwd --connected-device
`

**Comment by lu769257351** [comment]
这问题有人知道怎么解决吗？我也遇到了
