### ISSUE TITLE
can aab trans to full split apk?

### ISSUE THREAD

**Issue by whc1998** [google/bundletool#271]
hello !
Is it possible to provide to convert aab files to base and split apk, each apk contains all the code and resources of the respective module？

like this :
test.aab 
       --> base.apk , split1.apk , split2.apk

**Comment by ymakhno** [comment]
Yes. You need to disable all optimizations: abi, density, language and next use `build-apks` command. If you use Android Gradle Plugin you can disable it via this configuration: https://developer.android.com/guide/app-bundle/configure-base.
