### ISSUE TITLE
Intent filter elements are not merged properly between feature modules and base modules

### ISSUE THREAD

**Issue by BenSchwab** [google/bundletool#273]
**Describe the bug**
Intent filter elements are not merged from between a dynamic feature manifest and base feature manifest.
I believe this is because there is a typo in AndroidManifest.java: https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/model/AndroidManifest.java#L76
` public static final String INTENT_FILTER_ELEMENT_NAME = "intent-filder";`  should be 
` public static final String INTENT_FILTER_ELEMENT_NAME = "intent-filter";`

**Bundletool version(s) affected**
1.9.0

**Stacktrace**
N/A

**To Reproduce**
Create a dynamic feature with a manifest for an activity that contains an intent filter. In the base apk create a manifest entry for the same activity with the same intent filter.

Note that a universal apk only contains the intent-filter from the dynamic feature module.

**Expected behavior**
Universal apk should have the intent-filters from the base module and the dynamic feature module.

**Known workaround**
N/A

**Environment:**
OS: [e.g. iOS 10.3.3]

**Additional context**

**Comment by ymakhno** [comment]
Fixed in 1.9.1.
