### ISSUE TITLE
Real AdMob ads not showing after using  bundletool commands to load connected device

### ISSUE THREAD

**Issue by joes0451** [google/bundletool#274]
I'm not using Android Studio, I'm building everything through the command line.

I'm creating an App Bundle, unobfuscated and as a release, and using bundletool's 'build-apks' and 'install-apks' commands
to install to the connected device.  The app runs, and test ads show, but real AdMob ads are
not showing.  Everything works fine when built as an .apk.

      (Command)sb: 'SET PATH="C:/Program Files (x86)/Java/jdk1.8.0_20";%PA
TH%&&java -jar C:/bundletool-master/bundletool-all-1.8.2.jar build-apks --bundle
="C:/Android/Dev/G_GameNew/app/build/outputs/bundle/release/app.aab" --output="C
:/Android/Dev/G_GameNew/output.apks" --connected-device --overwrite --verbose --
ks=C:/Android/Dev/keystore/test-release-key.jks --ks-pass=pass:xxxxxxxxxx --ks-k
ey-alias=test-alias --key-pass=pass:xxxxxxxxxx

     (Command)sb: 'SET PATH="C:/Program Files (x86)/Java/jdk1.8.0_20";%PA
TH%&&java -jar C:/bundletool-master/bundletool-all-1.8.2.jar install-apks --apks
="C:/Android/Dev/G_GameNew/output.apks"

After running it the game runs but the AdMob ads never show up, with the only
changes being using a different keystore for the App Bundle then for the .apk.

The "main.java" portion of the game:

    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        Log.d(TAG, "\n\n=================================\nonCreate()");
   
        AndroidApplicationConfiguration cfg = new AndroidApplicationConfiguration();
        cfg.useAccelerometer = false;
        cfg.useCompass = false;
   
        // Do the stuff that initialize() would do for you
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
   
        //setContentView(R.layout.my_layout);
        setContentView(R.layout.game_main);
       
        // Initialize the Mobile Ads SDK.
        MobileAds.initialize(this, new OnInitializationCompleteListener()
        {
            @Override
            public void onInitializationComplete(InitializationStatus initializationStatus)
            {
            }
        });

        adView = findViewById(R.id.ad_view);
        //adView = new AdView(this);
       
       
        if ( adView == null )
            Log.d(TAG, "adView null");
        else
            Log.d(TAG, "adView not null");
/**/            

        adView.setAdListener(new AdListener()
        {
            @Override
            public void onAdOpened()
            {
                Log.d(TAG, "\nonAdOpened()");
            }
           
            @Override
            public void onAdLoaded()
            {
                Log.d(TAG, "\nonAdLoaded()");
            }

            @Override
            public void onAdClicked()
            {
                // Code to be executed when the user clicks on an ad.
                Log.d(TAG, "onAdClicked()");
            }
       
            @Override
            public void onAdClosed()
            {
                // Code to be executed when the user is about to return
                // to the app after tapping on an ad.
                Log.d(TAG, "onAdClosed()");
            }
        });
/**/

        gameView = initializeForView(new GameTest(), cfg);
       
        if ( gameView == null )
            Log.d(TAG, "(initializeForView())gameView null");
        else
            Log.d(TAG, "(initializeForView())gameView not null");
           
           
        //findViewById<FrameLayout>(R.id.game_container).addView(gameView);
        FrameLayout frameLayout = (FrameLayout)findViewById(R.id.game_container);
        frameLayout.addView(gameView);
       
        // Create an ad request.
        AdRequest adRequest = new AdRequest.Builder().build();

        if ( adView == null )
            Log.d(TAG, "(2)adView null");
        else
            Log.d(TAG, "(2)adView not null");
/**/            
       
        if ( adRequest == null )
            Log.d(TAG, "(AdRequest.Builder().build())adRequest null");
        else
            Log.d(TAG, "(AdRequest.Builder().build())adRequest not null");
   
        // Start loading the ad in the background.
        adView.loadAd(adRequest);
       
       
       
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
   
    <FrameLayout
        android:id="@+id/game_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/ad_view"
        android:layout_alignParentTop="true" />

    <com.google.android.gms.ads.AdView
        android:id="@+id/ad_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        app:adSize="BANNER"
        app:adUnitId="@string/banner_ad_unit_id" />
       
</RelativeLayout>
       

And in the logcat output:

D/G_GameNewActivity( 6389):
D/G_GameNewActivity( 6389):
D/G_GameNewActivity( 6389): =================================
D/G_GameNewActivity( 6389): onCreate()

D/G_GameNewActivity( 6389): adView not null
D/GameTest( 6389):
D/GameTest( 6389): GameTest() constructor

D/G_GameNewActivity( 6389): (initializeForView())gameView not null
D/G_GameNewActivity( 6389): (2)adView not null
D/G_GameNewActivity( 6389): (AdRequest.Builder().build())adRequest not null

So it's getting non-null returns from the important calls
but the AdMob ads don't show, but they work fine when using an .apk

Since I'm not building it with Android Studio, it's possible that some important "extra" settings are
not being used in the build, so I would appreciate you letting me know of anything that I could try
to fix it. 

UPDATE:

In a way using the bundletool commands with real AdMob ads is still "broken", the real ads won't show when run. BUT if you have your app's App Bundle set up with the proper AdMob Ids, after you upload your app, in the Play Store, select your app and under Policy->App Content->Ads->Manage make sure that the "Yes my app contains ads" is selected, then when people download it the real AdMob ads WILL SHOW.

So there seems to be some difference between what the Play Store does with building the App Bundle and using the bundletool commands to load it on a connected device.  In that case real Admob ads don't show, so I wouldn't say that the issue is "resolved", but you can get your ads to show from the Play Store if everything is set up right.

 Thanks!!

**Comment by ymakhno** [comment]
This issue doesn't relate to `bundletool`. Probably this is something specific to AdMob.
