### ISSUE TITLE
build-apks - question regarding signing

### ISSUE THREAD

**Issue by bengrah-miller** [google/bundletool#276]
Hi there,

We're using Ionic/Cordova framework to develop Android apps. We currently generate a release using the following command:

`ionic cordova build android --release --prod --buildConfig=build.json`

The `build.json` file contains the keystore information, so the final output AAB file generated will be signed already, we then zipalign the file so everything is ready for upload into the Play Store.

With _bundletool,_ you can install the app locally by first using the `build-apks` command, followed by running the `install-apks` command on the resulting file. The `build-apks` command can be used without the `--ks` and `--ks-key-alias` commands for signing, but if you do this, the app is signed anyway using the `debug.keystore`:

`INFO: The APKs will be signed with the debug keystore found at 'C:\Users\bengrah\.android\debug.keystore'.`

I had a couple of questions around this process I'd really appreciate if someone could answer:

1. Are there any concerns around re-signing files when they have already been signed? e.g. I've already got a signed AAB file, is the resulting APKS file not signed already too or is the signing process being re-done here because the APKS file *isn't* signed at this point?
2. If you decide to not provide your keystore informationfor signing, and sign using the `debug.keystore` file, can this still be considered the same as using your own keystore to sign prior to upload into the Play Store? Are we for the most part doing like for like, regardless if it's a slightly different signing process?

Thanks,
bengrah

**Comment by ymakhno** [comment]
1. Bundletool signs APK files that it generates from input AAB file. It doesn't re-sign AAB file. As you mentioned above you can provide your own keystore via `--ks` flag if you wish to sign APKs with a specific key.
2. `build-apks` and `install-apks` do not modify your AAB file that you upload to Play Console they just produce/install APKs locally.

**Comment by bengrah-miller** [comment]
Great, thanks @ymakhno
