### ISSUE TITLE
How to compile the bundletool code when I add some feature which is based on the branch code.

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#28]
I just compile the code with gradle but the output jar was only 1.3M.

**Comment by plecesne** [comment]
The default build task will build the jar without dependencies. For the standalone tool, you want to execute the `executableJar` task.

**Comment by TamilanPeriyasamy** [comment]
@plecesne can't find com.android.bundle.* packages
Did you add any dependencies?

**Comment by aishang5wpj** [comment]
> I just tried the following command and it built successfully.
> 
> ```
> ./gradlew executableJar 
> ```
> 
> What command are you running? And what exception are you getting? Did you modify the `build.gradle`?

this command worked for me, and I got a jar file `bundletool-all.jar`  in directory `bundletool-master/build/libs/`.

`./gradlew executableJar ` 

but what should I do if I want to debug the project ? I import it into IntelliJ IDEA CE and create an application configuration for it , then I run it , it shows me the message bellow:

```
Error:(18, 36) java: 程序包com.android.bundle.Targeting不存在
Error:(19, 61) java: 程序包com.android.bundle.Targeting.TextureCompressionFormat不存在
Error:(20, 36) java: 程序包com.android.bundle.Targeting不存在
Error:(27, 38) java: 找不到符号
  符号:   类 TextureCompressionFormatAlias
  位置: 类 com.android.tools.build.bundletool.model.utils.TextureCompressionUtils
Error:(40, 44) java: 找不到符号
  符号:   类 TextureCompressionFormatTargeting
  位置: 类 com.android.tools.build.bundletool.model.utils.TextureCompressionUtils
Error:(53, 7) java: 找不到符号
  符号:   类 TextureCompressionFormatAlias
  位置: 类 com.android.tools.build.bundletool.model.utils.TextureCompressionUtils
Error:(52, 18) java: 找不到符号
  符号:   类 TextureCompressionFormatTargeting
  位置: 类 com.android.tools.build.bundletool.model.utils.TextureCompressionUtils
```

what mistakes with my steps ? @plecesne

**Comment by plecesne** [comment]
Look at my answer here: https://github.com/google/bundletool/issues/54#issuecomment-471490322

**Comment by aishang5wpj** [comment]
> Look at my answer here: [#54 (comment)](https://github.com/google/bundletool/issues/54#issuecomment-471490322)

good answer, still does not help me.

**Comment by plecesne** [comment]
Have you added all three source folders in the module? Can you show me a screenshot of how you've configured this?

**Comment by aishang5wpj** [comment]
> Have you added all three source folders in the module? Can you show me a screenshot of how you've configured this?

sure. here is my configuration, is this right ?

![image](https://user-images.githubusercontent.com/7829473/59507016-47333b80-8edc-11e9-89ce-dfca741e6e78.png)

**Comment by plecesne** [comment]
Make sure `java` and `proto` are selected as "Source Folders".

![bundletool-project](https://user-images.githubusercontent.com/1924185/59507586-5649c780-8ea3-11e9-821b-343a11887e9e.png)

**Comment by aishang5wpj** [comment]
It still doesn't work :(

![image](https://user-images.githubusercontent.com/7829473/59508003-17d1fe00-8edf-11e9-9440-c99b220748b0.png)
![image](https://user-images.githubusercontent.com/7829473/59508006-1a345800-8edf-11e9-84da-231ac6f9a449.png)

**Comment by plecesne** [comment]
Yeah, sorry, missing the generated files:

![bundletool-main](https://user-images.githubusercontent.com/1924185/59515055-2f48c100-8eb6-11e9-993a-aa1e920c4d70.png)

And for tests, add the source, and add a dependency on main:

![bundletool-test0](https://user-images.githubusercontent.com/1924185/59515076-396abf80-8eb6-11e9-8882-f7f54eaa3c5f.png)
![bundletool-test](https://user-images.githubusercontent.com/1924185/59515088-3bcd1980-8eb6-11e9-8766-550e3ba60e96.png)

**Comment by aishang5wpj** [comment]
> Yeah, sorry, missing the generated files:
> 
> ![bundletool-main](https://user-images.githubusercontent.com/1924185/59515055-2f48c100-8eb6-11e9-993a-aa1e920c4d70.png)
> 
> And for tests, add the source, and add a dependency on main:
> 
> ![bundletool-test0](https://user-images.githubusercontent.com/1924185/59515076-396abf80-8eb6-11e9-8882-f7f54eaa3c5f.png)
> ![bundletool-test](https://user-images.githubusercontent.com/1924185/59515088-3bcd1980-8eb6-11e9-8766-550e3ba60e96.png)

Thanks , it worked. In addition to this, there are some places to pay attention to.

1. source code does not contains `build` folder, you need run `./gradlew executableJar` to generate it.
2. you must remove all config from `bundletool-master`  first in configuration panel, otherwise you cannot add `build` folder to `main`.

![image](https://user-images.githubusercontent.com/7829473/59588633-a2527180-911a-11e9-8e90-e7beed7bf5ba.png)

**Comment by plecesne** [comment]
Great, we should add this to the CONTRIBUTING files possibly.
Feel free to send the pull request if you're interested in helping out, otherwise I'll add it at some point myself :)

**Comment by Shihab-BD** [comment]
@plecesne I tried to run the source also, same "com.android.bundle" package not found. Is it coming from any dependency. Got no idea anyway.

**Comment by plecesne** [comment]
Follow the instructions from this thread, in particular make sure you ran gradlew and that you added the generated sources to the source folders.
