### ISSUE TITLE
Unable to add a jar dependency in android project

### ISSUE THREAD

**Issue by omkar-tenkale** [google/bundletool#286]
**Describe the bug**
Cannot compile android project when bundletool is added as jar dependency
```

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation files('libs/bundletool-all-1.10.0.jar')
```

**Stacktrace**
`The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.
`

**To Reproduce**
Steps to reproduce the behavior.
Add the bundletool jar dependency in app module's build.gradle

**Expected behavior**
App should compile and bundletool classes should be available to use

**Comment by omkar-tenkale** [comment]
As per my research and attempts, it's close to impossible

**Comment by ymakhno** [comment]
At the moment bundletool is not Android ready and can be run only inside JRE. There are no current plans to change it.
