### ISSUE TITLE
Bundletool doesn't respect ANDROID_SERIAL

### ISSUE THREAD

**Issue by nfischer** [google/bundletool#29]
**Is your feature request related to a problem? Please describe.**

Most Android tools support setting the `ANDROID_SERIAL` environmental variable when working with multiple devices. It looks like your tool has a `--device-id` flag, which probably does the same thing.

**Describe the solution you'd like**

Ok, so why is `--device-id` not good enough? The environmental variable is nice because it applies recursively to subprocesses. This means I can write a script which calls bundletool, and I don't have to add an explicit `--device-id` flag to **my** script just to make bundletool work.

`ANDROID_SERIAL` is documented in the adb help pages (it's equivalent to adb's `-s` flag).

**Describe alternatives you've considered**

Alternative is for me to explicitly check for my env var and pass it to bundletool with a flag. But it's pretty standard for tools to respect `ANDROID_SERIAL`, so I don't think this is an unreasonable thing to add to bundletool itself.

**Additional context**

No additional context, but I'm more than happy to implement this myself if you're willing to integrate it.

**Comment by plecesne** [comment]
Makes sense. Welcoming contributions :)
