### ISSUE TITLE
Missing APKs for [SCREEN_DENSITY] dimensions in the module 'base' for the provided device.

### ISSUE THREAD

**Issue by LianBai** [google/bundletool#294]
java -jar bundletool-all-1.10.0.jar build-apks --bundle=test.aab
 
Error: Missing APKs for [SCREEN_DENSITY] dimensions in the module 'base' for the provided device.
com.android.tools.build.bundletool.model.exceptions.IncompatibleDeviceException: Missing APKs for [SCREEN_DENSITY] dimensions in the module 'base' for the provided device.

**Comment by ymakhno** [comment]
This issue is not actionable as does not contain any steps to reproduce.
