### ISSUE TITLE
Baseline Profile missing from Universal Apk

### ISSUE THREAD

**Issue by kenshin171** [google/bundletool#295]
**Describe the bug**
Bundletool does not seem to bundle the baseline profiles located inside the folder `BUNDLE-METADATA/com.android.tools.build.profiles` in an aab into the universal apk.

**Bundletool version(s) affected**
Version: 1.11.0

**Stacktrace**
NA

**To Reproduce**
commands used to generate universal apk
```
bundletool build-apks --bundle=output.aab --output=output.apks --ks=path/to/my/keystore/keystore --key-pass="pass:password" --ks-key-alias=release --ks-pass="pass:keypass" --mode=universal --overwrite

unzip output.apks universal.apk
```

**Expected behavior**
When i inspect the aab in android studio, i can see that, there is indeed baseline profile files at `BUNDLE-METADATA/com.android.tools.build.profiles`, but after I create the universal apk. when i inspect the apk, i cannot find the baseline profile files in the `assets/dexopt` folder at all.

**Known workaround**
Nil

**Environment:**
OS: MacOs 12.4

**Additional context**

**Comment by ymakhno** [comment]
Fixed in 1.11.1.
