### ISSUE TITLE
Error: Unrecognized command 'not-a-command'

### ISSUE THREAD

**Issue by garawaa** [google/bundletool#299]
**Describe the bug**
Error: Unrecognized command 'not-a-command'.
**Bundletool version(s) affected**
Version: [e.g. 0.3.3]
1.11.0
**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.
Error: Unrecognized command 'not-a-command'.
**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.
open bundetool project in intellij idea and gradle build
**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS: [e.g. iOS 10.3.3]
windows 10
**Additional context**

**Comment by ymakhno** [comment]
Issue is not actionable as does not have steps to reproduce.
