### ISSUE TITLE
Using the build-bundle command need to provide modules as zip, but how to generate the module as Zip.

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#30]
Dear Sir 

     Using the build-bundle command need to provide modules as zip, but how to generate the module as Zip.

thank very much.

**Comment by plecesne** [comment]
You can find the information here: https://developer.android.com/studio/build/building-cmdline#bundletool-build

**Comment by aishang5wpj** [comment]
this artical does NOT tell me how to generate the modul as zip, only tell me to use `gradlew assembleDebug` to generate an apk.

**Comment by plecesne** [comment]
Here's an extract of the page:

> #### Package pre-compiled code and resources
> 
> Before you use bundletool to generate an app bundle for your app, you must first provide ZIP files that each contain the compiled code and resources for a given app module. The content and organization of each module's ZIP file is very similar to that of the Android App Bundle format. For example, you should create a base.zip file for your app's base module and organize its contents as follows:
> 
> File or directory | Description
> -- | --
> manifest/AndroidManifest.xml | The module's manifest in protobuf format.
> dex/... | A directory with one or more of your app's compiled DEX files. These files should be named as follows: classes.dex, classes2.dex, classes3.dex, etc.
> res/... | Contains the module's resources in protobuf format for all device configurations. Subdirectories and files should be organized similar to that of a typical APK.
> root/..., assets/..., and lib/... | These directories are identical to those described in the section about the Android app bundle format.
> resources.pb | Your app's resource table in protobuf format.
> 
> After you prepare the ZIP file for each module of your app, you can pass them to bundletool to build your app bundle, as described in the following section.

**Comment by aishang5wpj** [comment]
@plecesne  I can see it when I switch chrome's language to English , but I can't see it when chromes's language is Chinese, so it made me misunderstand.
thank you.

**Comment by plecesne** [comment]
Oh, interesting, thanks for letting me know. I'll see if I can get this fixed.
