### ISSUE TITLE
Wrong result for bundletool 1.13.1 when get-size with --modules=base

### ISSUE THREAD

**Issue by saulsq** [google/bundletool#306]
**Wrong result for bundletool 1.13.1 when get-size with --modules=base**

**Bundletool version(s) affected**
Version: 1.13.1

**Precondition**
aab include base and assetpack(deliveryType = "install-time")

**Reproduce Step**

1. `java -jar bundletool-all-1.13.0.jar build-apks --bundle=test.aab --output=test.apks`

2. `java -jar bundletool-all-1.13.0.jar get-size total --human-readable-sizes --modules=base --apks=.\test.apks`
**Console result:**
MIN,MAX
122.37 MB,126.95 MB

3. `java -jar bundletool-all-1.13.1.jar get-size total --human-readable-sizes --modules=base --apks=.\test.apks`
**Console result:**
MIN,MAX
153.44 MB,158.02 MB

**Expected behavior**
The result should same with **Step 2**, and Google Play Result, and it should not include asset pack module

**Question**
Is it a feature or a bug?

We use bundletool to monitor aab base module size for 150M limit
We can not use the step3 result beacause Google Play 150M limit is not include **asset pack** size

The changes may be from 1.13.1 changes:
`extract-apks command: install-time asset modules are now extracted regardless of the requested module names.`

Code:
https://github.com/google/bundletool/commit/db279345aa9503874b0778662ffbddb6499309b9?diff=split#diff-33e0b2fad972f0577251fe5da77859a36440bfb56e64a412e1f12efc23b69939R127

https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/device/AssetModuleSizeAggregator.java#L127

**Comment by ymakhno** [comment]
Fixed in 1.13.2.
