### ISSUE TITLE
build-apks Error when executing command: ..aapt2 

### ISSUE THREAD

**Issue by rizreynal** [google/bundletool#315]
**Describe the bug**
I've a backend service that will generated .apks using an existing .aab file .
let say name of .aab file is _MobileApp-1.aab_ and expected output is _MobileApp-1.apks_
full command below 
`java -jar bundletool-all-1.14.0.jar build-apks --overwrite --mode=universal --bundle=MobileApp-1.aab --output=MobileApp-1.apks --ks=path_keystore.jks --ks-pass=pass:keystorepass --ks-key-alias=keystore_alias_key --key-pass=pass:key_pass_value`

Noted : it's just happened to some server . 

**Bundletool version(s) affected**
Version: [1.3.0] or using latest version [1.14.0]

**Error LOG**

> [BT:1.14.0] Error: Error when executing command: [/tmp/AutoValue_BuildApksCommand7888017164090094054/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/3895682706891686379/binary2.apk, /tmp/3895682706891686379/proto1.apk]
> com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Error when executing command: [/tmp/AutoValue_BuildApksCommand7888017164090094054/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/3895682706891686379/binary2.apk, /tmp/3895682706891686379/proto1.apk]
> 	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
> 	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:64)
> 	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
> 	at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:71)
> 	at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:158)
> 	at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:125)
> 	at com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$convert$3(Aapt2ResourceConverter.java:105)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
> 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: java.io.IOException: Cannot run program "/tmp/AutoValue_BuildApksCommand7888017164090094054/output/linux/aapt2": error=13, Permission denied
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
> 	at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:44)
> 	... 11 more
> Caused by: java.io.IOException: error=13, Permission denied
> 	at java.lang.UNIXProcess.forkAndExec(Native Method)
> 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
> 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> 	... 12 more
> 

Additional info : 
Storage
> df -h 
> \Filesystem                               Size  Used Avail Use% Mounted on
> tmpfs                                    5,8G  2,8M  5,8G   1% /tmp
> 
Java Version
> [app@app Test]$ java -version
> openjdk version "1.8.0_362"
> OpenJDK Runtime Environment (build 1.8.0_362-b08)
> OpenJDK 64-Bit Server VM (build 25.362-b08, mixed mode)

**To Reproduce**
prepared file .aab and keypass 

**Expected behavior**
No error found , and file apks has been generated . 

**Known workaround**
I've trying to execute using sudo . 
executed using latest version bundletool [1.14.0]. 
executed to other os .. Noted : it's just happened to some server . 

**Environment:**
running bundletool under OS: [Centos 7 (Core)]
NAME="CentOS Linux"
VERSION="7 (Core)"

**Comment by rizreynal** [comment]
Work well after I adding option aapt path 

java -jar bundletool-all-1.14.0.jar build-apks --overwrite --mode=universal --bundle=MobileApp-1.aab --output=MobileApp-1.apks --ks=path_keystore.jks --ks-pass=pass:keystorepass --ks-key-alias=keystore_alias_key --key-pass=pass:key_pass_value **--aapt2=<path_aapt>/aapt2** 

I get aapt2 linux by gradle or **bundletool-1.14.0/build/resources/main/linux/aapt2**

am still wondering why bundletool-all-1.14.0.jar doesn't have executed aapt2 without adding optional path aapt2

**Comment by ymakhno** [comment]
If aapt2 path is not provided bundletool just extracts aapt2 into some temp directory and next tries to execute it. It works on most developer's machines but on servers ability to execute binaries from temp dir might be revoked.
