### ISSUE TITLE
Support downgrading APKs

### ISSUE THREAD

**Issue by nfischer** [google/bundletool#32]
**Is your feature request related to a problem? Please describe.**

It would be nice to have the option to downgrade APKs on debuggable devices (i.e., install an *older* versionCode than what is currently installed). Specifically, this should match `adb install -d` behavior.

**Describe the solution you'd like**

I think it's fine to pass `-d` on `user`, `userdebug`, `eng` devices, I think package manager will simply ignore the request to downgrade if the device is not debuggable. This is how `adb install -d` seems to work.

**Describe alternatives you've considered**

The alternative is for our script to first uninstall the on-device APK, and to then install the new APK. This poses some issues: what if the uninstall succeeds but the install fails for some unexpected reason? The device is now in a worse state than before, when the preferred outcome would be to leave the original APK on the device.

We currently perform this workaround for user devices, but it would be nice to avoid it whenever possible, and I think there's value in matching `adb install`'s features whenever possible.

**Comment by plecesne** [comment]
Flag `--allow-downgrade` now available in the `install-apks` command in release 0.7.1.

**Comment by nfischer** [comment]
Thanks, @plecesne! Seems to work just like `adb install -d`, which is exactly what we needed.

Although, it looks like this still needs help documentation?

```sh
$ java -jar "$BTOOL" version
0.7.1
$ java -jar "$BTOOL" help | grep 'allow-downgrade' # no docs for this option
$ java -jar "$BTOOL" help install-apks | grep 'allow-downgrade' # not here either
```

**Comment by plecesne** [comment]
Oh right, well spotted. Stupid copy/paste. It'll be fixed in the next release.
