### ISSUE TITLE
Problem regarding 64bits libraries.

### ISSUE THREAD

**Issue by erastod** [google/bundletool#329]
Im using the option strip 64 bits libraries, but they are still being delivered. Is there any option to not deliver them at all.
This is my code for config.json
`{
  "optimizations": {
    "splitsConfig": {
      "splitDimension": [
        {
          "value": "ABI",
          "negate": true
        },
        {
          "value": "SCREEN_DENSITY",
          "negate": true
        },
        {
          "value": "LANGUAGE",
          "negate": true
        }
      ]
    },
	"uncompressDexFiles": {
      "enabled": false,
	  "uncompressedDexTargetSdk": "0"
    },
	"uncompressNativeLibraries": {
      "enabled": false	  
    },
	"standaloneConfig": {
      "strip64BitLibraries": true,
      "dexMergingStrategy": "MERGE_IF_NEEDED"
    },
  },
  "compression": {
    "uncompressedGlob": ["lib/arm64-v8a/**"]
  }
}

`

**Comment by ymakhno** [comment]
'strip64BitLibraries' option is only applicable to standalone/universal APKs. For devices with Android L and above where splits are served 64-bit libraries is Google Play requirement. 

Basically you can just remove 64-bit libraries from `lib/` folder if you app supports only 32-bits but you won't be able to upload such AAB to Google Play and look for alternative stores to publish your app.
