### ISSUE TITLE
Add a way to install all modules with install-apks

### ISSUE THREAD

**Issue by chrisbanes** [google/bundletool#33]
**Is your feature request related to a problem? Please describe.**
Currently you have to manually list all modules on `install-apks --modules` to install everything. Ideally we'd have a way install everything easily.

**Describe the solution you'd like**
Ideally I'd like a `install-apks --all-modules` flags to install all modules in the `.apks` file

**Describe alternatives you've considered**
install-apks --modules <list_all_modules>

**Comment by plecesne** [comment]
This was fixed in 0.8.0, with the special value `_ALL_` for the flag `--modules`.
