### ISSUE TITLE
Different get-size result between local and server build

### ISSUE THREAD

**Issue by fanjavaid** [google/bundletool#336]
Hello, i use bundletool to get the app size and implemented in the pipeline Job. But i get the different result between my local and server.  I still figuring out what the difference, because I already set the same `device-spec`.

The closest version with Google Play console App size results is from my local build.

Command:
```
java -jar /usr/local/bin/bundletool.jar build-apks --bundle=app-release.aab --output=app-release.apks --device-spec=device-spec.json
java -jar /usr/local/bin/bundletool.jar get-size total --apks=app-release.apks --device-spec=device-spec.json

```
AAB and APKS build in the server give the results:
```
MIN,MAX
39850203,39850203
```

AAB in the server, APKS build locally results:
```
MIN,MAX
40287939,40287939
```

Maybe there are some insights what makes it different.

Thank you.

**Comment by ymakhno** [comment]
Just a wild guess, under the hood `get-size` command uses GZIP deflater which is part of Java API. Might be that you have different JRE with different deflate implementation on server and locally.

Might make sense to try on the same version of bundletool + JRE.
