### ISSUE TITLE
Add "dump badging" command

### ISSUE THREAD

**Issue by baole** [google/bundletool#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

We use "aapt dump badging" to get meta data of an .apk file. It's nice to have similar solution for .aab file.

**Comment by plecesne** [comment]
This feature is coming in the next release of bundletool (hopefully next week). Stay tuned!

**Comment by TamilanPeriyasamy** [comment]
How to print other xml file values(e.g base/res/layout/activity_main.xml)

**Comment by plecesne** [comment]
Please file a separate feature request for this.

**Comment by TamilanPeriyasamy** [comment]
I have replace the manifest file path to separate xml file.
code:
  ZipPath manifestPath = ZipPath.create(moduleName.getName()).resolve("res/anim/abc_fade_in.xml");

Output is:
 <alpha xmlns:android="http://schemas.android.com/apk/res/android" android:duration="@android:integer/config_mediumAnimTime" android:fromAlpha="0.0" android:interpolator="@android:anim/decelerate_interpolator" android:toAlpha="1.0"/>

this is correct way....????
