### ISSUE TITLE
Unable to sign apk

### ISSUE THREAD

**Issue by wq1110** [google/bundletool#342]
![1691583295184](https://github.com/google/bundletool/assets/49897943/89681d1f-0655-411e-845a-8ab08a6889bc)

1.15.4 version

**Comment by wq1110** [comment]
Command line add ： --mode=universal   
it still doesn't work out

**Comment by ymakhno** [comment]
It is unclear what is the problem here. If you believe this is bundletool issue please create a new issue with proper description and steps to reproduce.
