### ISSUE TITLE
Gradle task to generate bundle and universal apk

### ISSUE THREAD

**Issue by AndreSand** [google/bundletool#35]
**Is your feature request related to a problem? Please describe.**
Our Daily CI builds and outputs APKs to S3 bucket and QA/Engineers use this build for testing, but now with Android App Bundles we need to build, then using bundletool.jar convert bundle *.aab to universal APK and output to S3 bucket. I think more teams will also face this situation.

**Describe the solution you'd like**
It will be nice if the Gradle task `$./gradlew bundleRelease` generated the bundle *.aab and the universal.apk

**Describe alternatives you've considered**
Creating a custom Gradle task and to after building the bundle.

**Comment by plecesne** [comment]
Please file bugs for the Android Gradle plugin in their issue tracker:

https://developer.android.com/studio/report-bugs
