### ISSUE TITLE
libs file(*.so) inside split apk doesn't extracted to folder "lib" in App Bundle

### ISSUE THREAD

**Issue by rafirafika** [google/bundletool#39]
Hello team, 
I have problem when try to read libs file (*.so) within app bundle.
commonly, if we install installer file (*.apk), this .apk file will be extracted in the device on folder data/app/packageName and inside it there are "lib" folder that contain libs file.
But when I installed app bundle and when bundle is extracted on the device my folder "data/app/mypackageName/lib"  is empty. all my libs files (*.so) that I need still in splitApk.apk file

preview for extracted bundle file in device
![bundle](https://user-images.githubusercontent.com/1444252/50512791-8f91a500-0ac6-11e9-8224-532f86da585d.PNG)

preview for extracted .apk file in device
![apk file](https://user-images.githubusercontent.com/1444252/50512864-fc0ca400-0ac6-11e9-86f4-957e69b3629a.PNG)

command that I used to install aps bundle is : 
install-apks --apks=!BASENAME_PATH!.apks --modules=dlc_module

Question : 
Could I get all libs(*.so) files such as if we use .apk file as installer? because I need this file to handle security system in my apps
If I couldn't , Could you please give me some advice?

Btw, sorry if my question is not clear enough, my english is very bad.

**Comment by Almhlhk92** [comment]
![google-play-badge](https://user-images.githubusercontent.com/45525683/50550531-7124d880-0c83-11e9-90bd-1ae9cce89979.png)

**Comment by rafirafika** [comment]
Hy @plecesne thanks for your info and suggestion. 
seems I'll choose to read native libs from Apk directly.

**Comment by trungnd90** [comment]
@plecesne  "There is a flag in Gradle to disable this feature" Could you give detail about this? I want to try disable it.

**Comment by plecesne** [comment]
You can set the property `android.bundle.enableUncompressedNativeLibraries=false` in the `gradle.properties`. Would you mind sharing why this is causing you issue?

**Comment by trungnd90** [comment]
I just want to have more free space to push some data into apk

**Comment by plecesne** [comment]
By compressing the native libraries, the APKs served to your users will be **bigger**! I explained this a bit better in https://github.com/google/bundletool/issues/118

Although the App Bundle looks bigger and the APK files look bigger, the compression performed over the wire will be more efficient, leading to smaller downloads, and the size on device will be saved as well since the platform will not have to extract it at install time (which would result in two copies of the native libraries on device: one compressed in the APK, and one uncompressed in the installation directory).

Note also regarding size limits that the Play Console doesn't not validate the size based on the size of the App Bundle but based on the download size of the generated APKs.

**Comment by rpattabi** [comment]
> You can set the property `android.bundle.enableUncompressedNativeLibraries=false` in the `gradle.properties`. Would you mind sharing why this is causing you issue?

@plecesne Thanks, but the correct property is `android.bundle.enableUncompressedNativeLibs`

We would like you to be aware that we couldn't use uncompressed native libs feature as we need to use the **path** of the .so files. For example, when we use [pure data](https://puredata.info/), a audio manipulating engine, we shall providing the native library path to its API for it to discover the custom `externals` that we built for it to consider in audio processing. So native library path is critical for our purposes.  If we leave native libs uncompressed in apk, the path returned by `ApplicationInfo.nativeLibraryDir` does not contain native libraries anymore. So puredata engine wouldn't discover our custom externals.

Hope that makes sense. I wonder if there is a way to get valid native libraries path even if we keep native libs uncompressed in the apk.

**Comment by plecesne** [comment]
Ah, sorry about the name, I'll edit my comment in case somebody finds it later.

Loading the library using `System.loadLibrary` (in java) or in `dlopen` (in C++) should just work on Android, the platform will find the library even if it's uncompressed in the APK. So I guess it depends how this SDK loads the library you're giving it.

**Comment by rpattabi** [comment]
Good to know that `dlopen` would work fine. Still there are libraries that need a lookup "path" to discover and load plugins/extensions in the form of `.so` files (like puredata mentioned above). This is typically the case with audio libraries. We used to supply them with the path provided by `ApplicationInfo.nativeLibraryDir`. As mentioned, this path is reported empty when native libs are uncompressed in the apk. Thus it doesn't work. So we could take advantage of this feature only if the platform provides a filesystem path that present native libs even though they still reside in apk.

Until then, `android.bundle.enableUncompressedNativeLibs=false` is critical for our purposes if we intend to use app bundle. We are glad to use app bundle as it reduced our app size by half! However, currently we get this warning (which is bit unsettling :--)

> WARNING: The option setting 'android.bundle.enableUncompressedNativeLibs=false' is experimental and unsupported.

**Comment by plecesne** [comment]
Depending on non-Android SDKs may require you to leave APKs compressed indeed.

Note that the warning you see was removed in 3.6 canary 3.

**Comment by riskycheng** [comment]
you can use :
getContext().getApplicationInfo().nativeLibraryDir;
to fetch the actual native lib path if you want to use these libs like export the env with these so libs;

**Comment by omarfuzzertest** [comment]
> android.bundle.enableUncompressedNativeLibs=false
It helped me a lot, I suffered a lot with this error

**Comment by vimalakshiadiga2601** [comment]
I have tried with android.bundle.enableUncompressedNativeLibs=false, unfortunately it does not create lib/<abi> folder on release builds

**Comment by 0xjacklove** [comment]
android {
packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
it works for me

**Comment by zchancode** [comment]
But there's a new problem here. if **libxxx.so** don't be extracted to **getContext().getApplicationInfo().nativeLibraryDir;**
1. i can't debug libxxx.so using ida
2. run **cat /proc/pid/maps**  doesn't show any address for libxxx.so.
3. it can prevent cracking or prevent debugging?
