### ISSUE TITLE
MacOS adb path not retrieved

### ISSUE THREAD

**Issue by rsavutiu** [google/bundletool#4]
**Describe the bug**
the command line tool is always asking me about adb path, even though ANDROID_HOME is set correctly.

**Bundletool version(s) affected**
0.3.3

**To Reproduce**
Steps to reproduce the behavior.
java -jar bundletool-all-0.3.3.jar get-device-spec --output...
"Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable.
com.android.tools.build.bundletool.exceptions.CommandExecutionException: Unable to determine the location of ADB. Please set the --adb flag or define ANDROID_HOME environment variable."
adb path is already set, terminal accepts adb command.

**Environment:**
MacOs

**Comment by plecesne** [comment]
What is the path to adb that you provide? (obfuscate names if necessary)
In particular, do you use "~" for home directory?  If so, could you try replacing it with the absolute path?

**Comment by rsavutiu** [comment]
If I provide it via the --adb optional, it will work. The question is why doesn't it work by default? I have adb set to path, it works from my terminal from any path.

**Comment by superbonaci** [comment]
Use `export ANDROID_HOME='xxx'` for environment variable

**Comment by cesards** [comment]
I think this issue should be closed @rsavutiu

**Comment by plecesne** [comment]
Closing this issue since specifying `ANDROID_HOME` environment variable should work.

**Comment by AdamSHurwitz** [comment]
@superbonaci May you please elaborate on where and how to implement this? **Use export ANDROID_HOME='xxx' for environment variable**

**Comment by plecesne** [comment]
@AdamSHurwitz This seems unrelated to bundletool. Are you able to run adb commands on the command line independently of bundletool?

**Comment by AdamSHurwitz** [comment]
@plecesne - Yes, **adb** works as expected in all other use cases. I created an export in my bash_profile as a workaround for now since the **--adb** flag does not work in the command.

**Comment by nfischer** [comment]
The `--adb` flag works fine for me. I generally use it as `--adb="$(which adb)"` to work around #27.

**Comment by ciaranbaselmans** [comment]
I'm still having the same issue as @holoduke on macOS 13.0.1
