### ISSUE TITLE
Larger installed size for tablets

### ISSUE THREAD

**Issue by sujan219** [google/bundletool#41]
**Describe the bug**
When I run "bundletool install-apks" on tablet, the application installed size was increased from 35MB to 47MB. This is really weird because it works fine with phones. Could you help me understand what is going wrong? Is there anything I should do differently for tablets?

**Bundletool version(s) affected**
Version: 0.7.2

**Environment:**
OS: 7.0.0

**Comment by plecesne** [comment]
I can think of two possible reasons:
- The tablet has a higher screen density than the phone, and the resources with higher resolutions take more space.
- If your app makes use of any native libraries (including from your dependencies), the tablet could be using x86 and the phone arm, and the size of the native libraries can vary quite a bit.

An easy way to find out is to use the "extract-apks" command (You may need to use "get-device-spec" first to extract the device specs of the device in a JSON format you can feed to the extract-apks command): Extract the APKs for each device, and compare them.

**Comment by sujan219** [comment]
The comparison that I am doing is not between phone and tablet. 
Here is the test that I ran:
1) Install the app from Android Studio to tablet as normal apk.
2) Check the installed size on disk and see that it is 35MB.
3) Uninstall the app
4) Install the app from bundle tool (using install-apk command) from .apks file to tablet.
5) Check the installed size on disk and see that it is 47MB.

The size should have gone down instead of going up. Could you let me know if I am missing something?

**Comment by plecesne** [comment]
What Android version is the tablet on? 
Does your app have any native libraries?
Also, how do you measure the size on disk? Is it from the Android storage settings or are you using adb shell or something else?

**Comment by sujan219** [comment]
I tried Nexus7 (5.0.2) and PixelC (8.0.0) tablets.
No, we don't have any native binaries in our app. We only have about 5 .aar files.
For measuring the size on disk, I checked Android storage from application settings.

**Comment by sujan219** [comment]
Sure let me do that and get back to you.

**Comment by sujan219** [comment]
@plecesne nevermind me. Turns out android studio was automatically stripping out resources while I ran directly from the android studio. The normal way of deploying apk and comparing that to using bundle tool showed positive results. So, I was running my test incorrectly. 

I will close the issue.
