### ISSUE TITLE
Error building apks at release mode with Dexguard

### ISSUE THREAD

**Issue by hectoruiz** [google/bundletool#42]
Hi good afternoon!
 I'm trying to build an android application at release version with the latest Dexguard version (8.03.04). I generated the bundle from Android Studio 3.2.1 by the "Build Bundle" button. 

When I execute the bundletool (version 0.7.2) command build-apks with flags connected device and the flags with the information about with my keystore credentials the ouput is:

**[BT:0.7.2] Error: Path of targeted native directory must be in format 'lib/<directory>' but found ' '.**

![image](https://user-images.githubusercontent.com/4199496/51052367-b4157300-15d6-11e9-8ba0-ada8f90b7aa9.png)

I checked the bundletool code and I found this validation:
https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/validation/NativeTargetingValidator.java#L52

looking for, I thinks, this folder:
https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/model/BundleModule.java#L59

and my bundle has this folder inside base folder with the following subfolders:
![image](https://user-images.githubusercontent.com/4199496/51052301-8cbea600-15d6-11e9-8774-2ad78a82215d.png)

![image](https://user-images.githubusercontent.com/4199496/51052629-84b33600-15d7-11e9-8731-30aaf7547e35.png)

I'll apreciate some help or comments about this issue. 
Thanks a lot! :)

**Comment by plecesne** [comment]
I can't find in bundletool's code a path where we would write an empty string for the native library directory.
Have you reached out to Dexguard? This looks like this issue could come from them.

**Comment by plecesne** [comment]
I believe Dexguard has since added support for App Bundle, so I will resolve this issue. Further questions related to Dexguard should be reported to Dexguard team.
