### ISSUE TITLE
Question: How to use this tool in Android device

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/bundletool#45]
Suppose I want to share/backup an app that was installed as an app-bundle.
I know how to collect the various APK files that are a part of the app-bundle (by looking at the paths of `packageInfo.applicationInfo.splitPublicSourceDirs` : https://developer.android.com/reference/android/content/pm/ApplicationInfo#splitPublicSourceDirs ) 

But is it possible to uninstall the app, and later install it using those APK files, and this library?

If so, how? Does it require a rooted device? Are the APK files all that is needed to restore the backup?

**Comment by plecesne** [comment]
This question isn't related to bundletool. Try stackoverflow for general questions around APKs and the possibilities of the Android SDK.

**Comment by AndroidDeveloperLB** [comment]
Why isn't it?
It states it on the main page of the repository:

"Install APK(s) from the APK Set compatible with a connected device."

What is it used for, then?

I was told to ask about it from here:
https://forums.raywenderlich.com/t/android-app-bundles-getting-started-raywenderlich-com/58453/13?u=ad_lb

Can it be used on Android? Or only on PC ?

**Comment by plecesne** [comment]
If you have a list of APKs that is not in an APK Set generated by bundletool, then you should use directly "adb" to install them to a connected device:

```
adb install-multiple <apk1> <apks> <etc.>
```

**Comment by AndroidDeveloperLB** [comment]
@plecesne I see. Is it possible even for non-rooted devices, though?

**Comment by plecesne** [comment]
Sorry, but this is outside of the scope of bunldetool. Try stackoverflow.

**Comment by AndroidDeveloperLB** [comment]
OK thank you
