### ISSUE TITLE
Installation size on devices significantly larger with bundletool

### ISSUE THREAD

**Issue by mardann** [google/bundletool#48]
Our app compiles to ~45mb .apk in debug build, and occupies similar space on devices.
we used the bundle-tool (BT) to build a .aab file and simulate installations - results were promising!
 BT reported that final installations would  range between 24mb to 37mb, while the core package would be 20mb.

**Problem:**
end result on devices is significanlty larger - as seen in the devices settings/app-manager
- for Nexus5x (xxhdpi, api 26)- installation with .aab occupies 58mb (compared to ~45mb with .apk)
- for Samsung Note4 (xxxhdpi, api 23) - installation occupies **129mb**(!!!!)

what is happening here? where are all these extra mb's be coming from??

**Additional context:**
- .aab was compiled and installed on devices using both Android-Studio and bundle-tool independently, several times
- our app does not have any native libraries, is written in Java and Kotlin, no flavores, and one language
- .aab based on debug-build
- .aab was analysed with apk-analyser and confirmed BT report 
- clean installations ensured (previous version explicitly deleted)
- workstation: MacbookPro 13", 2015, Mojave 10.14.2
- IDE: Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

- this problem seems similar to issue #41, which was closed without being resolved
 
**Bundletool version(s) affected**
Version: 0.8.0

![app install with bundle](https://user-images.githubusercontent.com/13745861/52328693-283a0f80-29f9-11e9-94de-368d41b7c1f3.png)
![app install with apk](https://user-images.githubusercontent.com/13745861/52328704-2e2ff080-29f9-11e9-9d3b-922548f4997a.png)

**Comment by plecesne** [comment]
Thanks for the detailed bug report.

First, note that `bundletool get-size` command calculates the download size, not the installation size on disk. Size on disk includes optimized dex files, the size of uncompressed native libraries (I understand you don't have any in your app), etc.

Now, it's not obvious what is the source of the problem here. Would you be able to share with me the AAB and APK you are comparing? If you put it on a shared drive and give me the link, I'll request read access so I can download them.

Can you also verify that the dex files are the same in both the AAB and the APK, to make sure we're comparing the same app.

**Comment by plecesne** [comment]
We would need more data to consider this an issue in bundletool. 
Note that different Android devices optimize dex files and native libraries differently, some of which may lead to much increased size on the device. 
Having an AAB and APK (with same dex and native libraries) that reproduces this issue would be very helpful. Are you able to share them as I suggested in my previous comment?

**Comment by mardann** [comment]
Sorry for not replying. Obviously you need our .apk to examine, but I need approval of managers to share, and this may not be possible due to security concerns.

**Comment by plecesne** [comment]
Alternatively you can reach out to [Play Console support](https://support.google.com/googleplay/android-developer/answer/7218994?hl=en) and give them your package name. I can take on the investigation from there.

**Comment by ymakhno** [comment]
Inactive issue.
