### ISSUE TITLE
Integrate bundletool into AndroidStudio

### ISSUE THREAD

**Issue by rsavutiu** [google/bundletool#5]
**Is your feature request related to a problem? Please describe.**
The command line tool is very hard to use, lots of commands, lots of paths need to be set, etc.
It also seems to barely work on Mac.

**Describe the solution you'd like**
Could you just integrate building bundles, extracting apks from bundles and installing correct apk per connected device into the Android Studio configuration?
The reason why I want to do this is that the bundle is broken compared to my normal release apk, it produces different, wrong results. So I need to test my bundle before hand, and the only way to do this is via this command line tool

**Describe alternatives you've considered**
The alternative would be to create my own run configuration in AndroidStudio?

**Comment by plecesne** [comment]
This is already integrated in Android Studio 3.2.0 Preview (Canary 14).

See: https://developer.android.com/guide/app-bundle/build#deploy_from_bundle

**Comment by rsavutiu** [comment]
"If you build an app bundle for a debug version of your app, Android Studio automatically signs your app bundle with a debug signing key, and you can use bundletool to deploy your app from the app bundle to a connected device."

Could we NOT use bundletool and just have your command line integrated into AndroidStudio?

So, let's suppose I have  the .aab. Can I just then run it on my device, from Android Studio?

The reason I need to do this is because my reflective loading of resources from an internal module works after proguard in an apk, but not in a .aab. So I want to debug it and fix it.

**Comment by plecesne** [comment]
I see.
Currently, only App Bundles built with Android Studio can be deployed with Android Studio. I would recommend you file a feature request on Android Studio to add support for deploying App Bundles that have been built outside Studio.
See https://developer.android.com/studio/report-bugs to get the link to their issue tracker.
