### ISSUE TITLE
Unable to use bundletool.

### ISSUE THREAD

**Issue by filipedelimabrito** [google/bundletool#51]
**Describe the bug**
After downloading the latest bundletool version (0.8.0) I'm unable to use it as show below:

<img width="419" alt="screen shot 2019-02-26 at 23 15 44" src="https://user-images.githubusercontent.com/11776825/53453735-e2330300-3a1c-11e9-9bb1-cda7573d777c.png">

**Bundletool version(s) affected**
Version: 0.8.0

**To Reproduce**
Just download the .jar file from the [release page](https://github.com/google/bundletool/releases) to get that error.

**Expected behavior**
bundletool should be launched.

**Environment:**
OS: MacOS 10.14.3

**Comment by plecesne** [comment]
Downloading the jar shouldn't trigger this alone. I assume you also tried to execute it somehow.

Note that the jar you can download from the releases page is not an executable, it is to be used with the java command line, e.g.

```
java -jar bundletool-all-0.8.0.jar help
```

**Comment by filipedelimabrito** [comment]
@plecesne I just figured it out (after reading this [article](https://medium.com/mindorks/android-app-bundle-part-2-bundletool-6705b50bea4c)). Isn't it a worth to put this instruction on the README or [here](https://developer.android.com/studio/command-line/bundletool)?

Closing the issue.
Thank you for you help.
