### ISSUE TITLE
How to preset some custom languages in the base-master apk?

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#52]
**Is your feature request related to a problem? Please describe.**
Some language for example jp zh , how to preset the jp and zh language in the base-master.apk,
because the two language is used by default in some areas.

**Describe the solution you'd like**
Bundletool can support the func . 

**Describe alternatives you've considered**
it maybe modify the languagesplitter.java

**Additional context**

**Comment by kvafy** [comment]
Can you please describe your use-case in deeper detail? Why is it a problem if non-default languages (ie. resources without any language qualifier) are delivered as standard language split APKs, instead of being directly in the base-master.apk?

**Comment by wopeiseqi** [comment]
I will try add code in languageSplitter.
