### ISSUE TITLE
How to import this source code project in idea? Should I use Intellij IDEA or Android Studio? It cannot be compiled and makes problems when I import it in Intellij IDEA 

### ISSUE THREAD

**Issue by aishang5wpj** [google/bundletool#54]
How to import this source code project in idea? Should I use Intellij IDEA or Android Studio? It cannot be compiled and makes problems when I import it in Intellij IDEA

**Comment by aishang5wpj** [comment]
![popo_2019-03-11  11-59-23](https://user-images.githubusercontent.com/7829473/54099621-2a76fb80-43f5-11e9-994c-ccdff8177f7d.jpg)

**Comment by plecesne** [comment]
* Right click on the project > "Open module settings"
* Make sure you have all three source folders added:
   * `bundletool/src/main`
   * `bundletool/build/classes/java/main`
   * `bundletool/build/generated/source/proto/main/java`

If that still doesn't work, in the build.gradle replace the `shadow` dependencies with `compile` dependencies (but don't submit this change please).

**Comment by aishang5wpj** [comment]
@plecesne Thanks for your reply, but it still doesn't work.

Here are my steps:

1.  File > New... > Project from exsisting sources
2. 
![popo01](https://user-images.githubusercontent.com/7829473/54173171-c53a0d80-44bb-11e9-9b76-3798281064d9.jpg)
3. 
![popo02](https://user-images.githubusercontent.com/7829473/54173173-c703d100-44bb-11e9-8a67-e28921ed492e.jpg)
4. in the build.gradle replace the shadow dependencies with compile dependencies
![image](https://user-images.githubusercontent.com/7829473/54173210-f0bcf800-44bb-11e9-8600-1539d28b586e.png)

Here is my project in intellij IDEA:
![image](https://user-images.githubusercontent.com/7829473/54173235-1ba74c00-44bc-11e9-81d8-ec4c48cd3d45.png)

It still doesn't work when compiled, seems like some files are lost.

![image](https://user-images.githubusercontent.com/7829473/54173319-65903200-44bc-11e9-9802-ea9586028cb8.png)

For example, this class cannot be found by IDEA, and I cannot find it in this git project too.

```
com.android.bundle.Devices.DeviceSpec
```

Can you make sure that if all files are published completely.

**Comment by plecesne** [comment]
These classes are generated from the protobuf files. It looks like you haven't configured `bundletool/build/generated/source/proto/main/java` to be one of the sources of the project.

**Comment by aishang5wpj** [comment]
but i cannot find `bundletool/build/generated/source/proto/main/java` in my project , is there anything wrong?

![image](https://user-images.githubusercontent.com/7829473/54249255-65566c00-457a-11e9-9f2f-0995a49758f2.png)

**Comment by plecesne** [comment]
I've tested on my machine from a freshly downloaded source code and it worked, so there doesn't seem to be a problem with the project. Maybe you need to build with gradle first or something.
I'm going to close the issue now since this is not really the place for technical support. May I suggest stackoverflow to continue with the resolution of your problem.

**Comment by aishang5wpj** [comment]
thanks for not helping me. 
 :(

**Comment by aishang5wpj** [comment]
There is another way to read the souce code. In fact, I create a project which contains the bundletool.jar and I can read the source code in it. Here is the code, I'll be pleasure if it can help people who meet the same problems with me.

https://github.com/aishang5wpj/bundletool

**Comment by plecesne** [comment]
Make sure `java` and `proto` are selected as sources.

![bundletool-project](https://user-images.githubusercontent.com/1924185/59507612-6eb9e200-8ea3-11e9-856c-cbec3e3b8172.png)
