### ISSUE TITLE
how to use "build-bundle" command to build a bundle?

### ISSUE THREAD

**Issue by aishang5wpj** [google/bundletool#55]
how to use "build-bundle" command to build a bundle?

I have an android project with two modules，so how should I do to build a bundle with "build-bundle" command ? 

Should I convert the module to an "zip" file? I tried but bundletools show me the message:

```
build-bundle --modules=/Desktop/develop/MusicLive/AppBundle/app,/Desktop/develop/MusicLive/AppBundle/dynamic_feature1 --output=/Desktop/AppBundle/result.aab 
```

![image](https://user-images.githubusercontent.com/7829473/54114450-6de95e00-4425-11e9-9663-80fe5f369002.png)

```
build-bundle --modules=/Desktop/develop/MusicLive/AppBundle/app.zip,/Desktop/develop/MusicLive/AppBundle/dynamic_feature1.zip --output=/Desktop/AppBundle/result.aab 
```

![image](https://user-images.githubusercontent.com/7829473/54114390-4d210880-4425-11e9-9cac-d3a216cc0ad4.png)

**Comment by plecesne** [comment]
The `build-bundle` command is meant to be used by build systems (e.g. Gradle). Studio has an "Build App Bundle" option from which you can build directly a Bundle.

If you work on a build system to build App Bundles from source code, then I invite you to look at [this documentation](https://developer.android.com/studio/build/building-cmdline#bundletool-build)

**Comment by aishang5wpj** [comment]
@plecesne  Thank you for your reply, I appreciate.

I know how to build a bundle in Studio, but as you know, Google and Google Play cannot be visited in China, so I want to design a mechanism like AppBundle, so I must know how does bundletools works, and if I can build a bundle without Studio and use source project only that may be a good way to know bundletools more.

So if I want to build a bundle without an studio, must I compile and package the source project like Studio before use "build-bundle" ?

Looking forward to your reply.

**Comment by plecesne** [comment]
The documentation I linked you to explains how to do that.
