### ISSUE TITLE
how to add bundletool.jar to the path

### ISSUE THREAD

**Issue by loudDD** [google/bundletool#56]
Sorry to bother , i am no developer but a tester ,and  i am little confused about add the .jar to the path which i can't find bundletool.jar with 'which'command .the location of .jar is d:\bundle
and i add the path to the system enviournment . but the appium-doctor still cannot find the .jar

Really thanks for the help!

**Comment by plecesne** [comment]
To execute bundletool, use

    java -jar bundletool-all.jar <command>

e.g. `java -jar bundletool-all.jar help`
