### ISSUE TITLE
How to set the BuildConfig.json in AndroidStudio when build the aab?

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#60]
How to set the BuildConfig.json in AndroidStudio when build the aab?  
when using the IDE, how to build aab and developer can point to BuildConfig.json

**Comment by kvafy** [comment]
Android Studio/Gradle generates the BundleConfig file based on the project configuration. Some options stored in the BundleConfig can be customized by various Gradle properties.

If this question is in relation to #59, then unfortunately Gradle currently does not support customization of master resource IDs.
