### ISSUE TITLE
APK signing does not conform to jarsigner specification

### ISSUE THREAD

**Issue by pplusplus** [google/bundletool#62]
Jarsigner tool creates signature and signature block files (.SF, .RSA) using the first 8 characters of the keystore alias all converted to upper case.

https://docs.oracle.com/javase/7/docs/technotes/tools/windows/jarsigner.html (The Signed JAR file)

Bundletool seems to generate APKs with the fixed filename CERT for signature and signature block files.

I'm unsure if this is by design but it is causing us issues when trying to read the signature and signature block files at runtime.

**Comment by kvafy** [comment]
The the jar signature specs ([1](https://docs.oracle.com/javase/tutorial/deployment/jar/intro.html), [2](https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#Signature_File)) don't prescribe the actual names of signature files, only their extensions. The jarsigner naming convention is an implementation detail of that particular tool.

Could you please explain in more detail the nature of your issues?

**Comment by pplusplus** [comment]
Understood - the issue arose from the fact that we were expecting the filename in the jarsigner format and not being found when trying to read the file into memory. 

Closing the issue on the basis that Bundletool conforms to the JAR file specification but will sign files differently to apksigner and jarsigner (i.e. is by design).
