### ISSUE TITLE
Open `parseBundleConfigJson` method in BuildBundleCommand or accept a `path` to a json file in BuildBundleComman.Builder.setBundleConfig

### ISSUE THREAD

**Issue by thalescm** [google/bundletool#63]
**Is your feature request related to a problem? Please describe.**
Bundletool is great for dealing with everything related to app bundles. Other build systems should not reimplement what is already implemented here. For example, we bundled `bundletool` inside [buck](http://buckbuild.com) to start building app bundles.
On `bundletool` commandline for building app bundles, you can specify a `json` configuration file in order to customize how the final bundle (and thus the generated apks) should behave. But when integrating the tool into other systems, you could only specify a [BundleConfig](https://github.com/google/bundletool/blob/master/src/main/proto/config.proto#L7) to be passed to the BuildCommand, through it's [builder](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/commands/BuildBundleCommand.java#L99).

**Describe the solution you'd like**
Make the the [parseBundleConfigJson](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/commands/BuildBundleCommand.java#L302) method public or accept a `path` to a json file in [BuildBundleComman.Builder.setBundleConfig](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/commands/BuildBundleCommand.java#L99)

**Describe alternatives you've considered**
Both alternatives already described

**Additional context**
N.A.

**Comment by kvafy** [comment]
Thank you for placing this question. Can you please explain your use case in more detail? Why is the Java builder API not a viable option - either to construct the BundleConfig object directly from the build configuration, or to parse an existing JSON file using the JsonFormat class?

**Comment by thalescm** [comment]
As explained in the issue, the builder api only accepts an `BundleConfig` object, and not a path to the json. So I'd have to parse the json myself and create the `BundleConfig` object, a logic that is already implemented (also shown on the issue description) but not opened.

So currently I'm having to duplicate this logic [here](https://github.com/facebook/buck/pull/2231/files#diff-746433e7e7e20b23247ddaa695ce810eR137)

**Comment by kvafy** [comment]
Ok, I agree there is value in having a convenience method for parity with command line usage.

The Java builder APIs across commands will be extended to also accept files instead of Java objects, where applicable. This will include also the `BuildBundleCommand.Builder.setBundleConfig`.

**Comment by thalescm** [comment]
Awesome! thanks a lot @kvafy!
