### ISSUE TITLE
Extension to get-size command: Print size in MB by default and add bytes support through an additional flag.

### ISSUE THREAD

**Issue by garg-ketki** [google/bundletool#65]
**Is your feature request related to a problem? Please describe.**
Bundletool offers great utility and commands to explore .aab file. We are using get-size command to measure the min and max size of apks. Currently, the output looks something as follows:
```
MIN,MAX
4600000,4800000
```
Is there a rationale behind printing the size in bytes? If possible, can we print the size by default in more readable format like MB and add support for bytes through an additional flag?

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by plecesne** [comment]
Hi,

Thanks for the feedback. Your request makes complete sense. This is something we'd like to do eventually but have been busy with other features so far. Note that we accept code contributions, should you want to add it yourself. 

Also, note that the current format is CSV, so an alternative is importing the result in a spreadsheet and format the result as desired.

**Comment by garg-ketki** [comment]
I have created an [MR](https://github.com/google/bundletool/pull/67) to address the change. Can you please review and let me know in your thoughts?

**Comment by ymakhno** [comment]
Similar functionality is provided in 1.5.0.
