### ISSUE TITLE
File types which should be left uncompressed are compressed when building from command line

### ISSUE THREAD

**Issue by benjaminRomano** [google/bundletool#70]
**Describe the bug**
When building an app bundle using command line (`bundletool build-bundle ...`). File types which are supposed to be left uncompressed (based on the list outlined here: https://developer.android.com/studio/build/building-cmdline#build_bundle) are compressed.

This leads to the assets to not be loaded or in the worst case crash. We specifically saw this issue when trying to load `.mp3`/`.mp4` assets.

**Bundletool version(s) affected**
Version: 0.9.0

**To Reproduce**
You should be able to reproduce by simply running the following
```
bundletool build-bundle --module="module.zip" --output="output.aab"
bundletool build-apks --bundle="output.aab" --output="output.apks" --mode="universal"
unzip -d output_apks output.apks
zipinfo output_apks/universal.apk | grep 'mp3|mp4|png' 
```

You should see some similar output:
```
-rw----     0.0 fat     2351 b- defN 80-000-00 00:00 res/raw/chat_hang_up.mp4
-rw----     0.0 fat     2337 b- defN 80-000-00 00:00 res/raw/generic_push.mp3
-rw----     0.0 fat     8847 b- stor 80-000-00 00:00 res/raw/left_call.mp4
-rw----     0.0 fat    12855 bx stor 80-000-00 00:00 res/raw/ringtone_bff.mp4
-rw----     0.0 fat    12845 b- defN 80-000-00 00:00 res/raw/ringtone_full.mp4
-rw----     0.0 fat    12159 bx stor 80-000-00 00:00 res/raw/ringtone_outgoing_bff.mp3
-rw----     0.0 fat    12159 bx stor 80-000-00 00:00 res/raw/ringtone_outgoing_full.mp3
-rw----     0.0 fat    11741 b- defN 80-000-00 00:00 res/raw/ringtone_twotone.mp3
-rw----     0.0 fat     5062 b- defN 80-000-00 00:00 res/raw/scanned.mp4
```

Some files have compression enabled (denoted by `defN`) which is incorrect and will not work properly.

**Expected behavior**
By default the file types listed as skipped should be properly skipped and left uncompressed.

**Known workaround**

We worked around this issue by passing in a bundle config that explicitly skips these assets by using the `uncompressedGlobs` option.

```
{
  "compression": {
    "uncompressedGlob": [
      "**/*.3g2",
      "**/*.3gp",
      "**/*.3gpp",
      "**/*.3gpp2",
      "**/*.aac",
      "**/*.amr",
      "**/*.awb",
      "**/*.gif",
      "**/*.imy",
      "**/*.jet",
      "**/*.jpeg",
      "**/*.jpg",
      "**/*.m4a",
      "**/*.m4v",
      "**/*.mid",
      "**/*.midi",
      "**/*.mkv",
      "**/*.mp2",
      "**/*.mp3",
      "**/*.mp4",
      "**/*.mpeg",
      "**/*.mpg",
      "**/*.ogg",
      "**/*.png",
      "**/*.rtttl",
      "**/*.smf",
      "**/*.wav",
      "**/*.webm",
      "**/*.wma",
      "**/*.wmv",
      "**/*.xmf"
    ]
  }
}

```

**Environment:**
OS: latest Mac OS

**Comment by plecesne** [comment]
This was a change in bundletool 0.8.0. See the [release notes](https://github.com/google/bundletool/releases/tag/0.8.0). 

We'll update the documentation on developer.android.com. Thanks for pointing it out.

**Comment by benjaminRomano** [comment]
Thanks
