### ISSUE TITLE
Support creating Universal APK with custom ABI split

### ISSUE THREAD

**Issue by benjaminRomano** [google/bundletool#89]
**Is your feature request related to a problem? Please describe.**
In our testing platform, we run tests on both 32-bit and 64-bit versions. We achieve this today by creating a "fat" apk that includes both 32-bit and 64-bit native libraries and then a 32-bit only apk. 

We've been using the `assemble` task to generate these apks, but now that we are investing in dynamic feature modules this no longer works. This is due to the fact to create an apk that includes dynamic feature modules requires generating an app bundle first. To create the "fat" apk with all dynamic feature modules is trivial as we can use the `--mode=universal` flag; however, we cannot create a "universal" apk that includes just 32-bit binaries. Also generating a standalone apk would also not work as we want this apk to include all screen densities.

**Describe the solution you'd like**
It would be nice to be able to generate a standalone apk that is split only on ABI.
Something like `--mode=universal --abi=armeabi-v7a`

**Describe alternatives you've considered**
I haven't tested this but I assume I could generate a new app bundle that disables splits on language and sreen density and extract apks from that instead, but that would be a bit cumbersome.

**Comment by kvafy** [comment]
The workaround with generating another bundle while having language & density splitting disabled would work.

However, _"universal apk that includes just 32-bit binaries"_ is something that bundletool (and the Play Store) will never generate and serve to devices, so you are testing APKs that won't exist. Is there a specific reason for requiring an APK with all screen densities in your tests? For example, the `extract-apks` and `install-apks` commands can identify the right APKs for a concrete device (`--connected-device` and `--device-spec` flags). Does that help your use case?

**Comment by benjaminRomano** [comment]
Sorry for slow response.

Long-term migrating everything to use `extract-apks` would be ideal, but we have a lot of infrastructure that's based around being provided an APK. Another concern with deferring apk generation and using `--connected-device` is that APK generation is a bit slow (Currently on 0.9.0. Might be better with latest). We would want to avoid incurring that cost as much as possible, but again that's an infra problem on our end. With that said, it might actually improve performance given that install times would be quicker...

For now I've just gone with generating two app bundles.
