### ISSUE TITLE
gradle-wrapper.properties needs to specify gradle-5.0

### ISSUE THREAD

**Issue by sleekweasel** [google/bundletool#91]
A fresh checkout fails to build with ./gradlew build

0.10.1

**Stacktrace**

> ./gradlew build
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.3'.

**To Reproduce**
> git clone https://github.com/google/bundletool.git
> cd bundletool
> ./gradlew build

**Expected behavior**

It builds.

**Known workaround**

patch gradle/wrapper/gradle-wrapper.properties:
+distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-all.zip

Linux

**Comment by kvafy** [comment]
This appears to be a problem when compiling bundletool with JDK 11.

Upgrading Gradle to 5.0 (as pointed out by @sleekweasel), and auto-value to 1.6.2 seems to do the trick. This will be fixed in a future version. Thanks!

**Comment by sleekweasel** [comment]
@kvafy Seems I also need to change this line to include -annotations:
```
+    shadow "com.google.auto.value:auto-value-annotations:1.6.2"
```

I'll update my pull request

**Comment by ymakhno** [comment]
Is not reproducible in the latest version.
